---
kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
    exclude:
      - pull_request

steps:
  - name: up
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - scripts/docker-login.sh
      - docker-compose -f docker-compose.drone.yml pull
      - docker-compose -f docker-compose.drone.yml up -d --build --force-recreate

  - name: test-develop
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - docker-compose -f docker-compose.drone.yml exec -e CODECOV_TOKEN=$${CODECOV_TOKEN} -T photoprism make all test-js test-codecov install migrate
    when:
      branch:
        - develop

  - name: test
    commands:
      - docker-compose -f docker-compose.drone.yml exec -T photoprism make all test install migrate
    when:
      branch:
        - master
        - release

  - name: down
    commands:
      - docker-compose -f docker-compose.drone.yml down
    when:
      status:
        - failure
        - success

  - name: deploy-preview
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - scripts/docker-login.sh
      - make docker-photoprism-preview
      - docker pull photoprism/photoprism:preview
      - make docker-docker-demo
    when:
      status:
        - success
      branch:
        - master

  - name: deploy-release
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - scripts/docker-login.sh
      - make docker-photoprism
    when:
      status:
        - success
      branch:
        - release

---
kind: pipeline
type: exec
name: pull-request

platform:
  arch: amd64
  os: linux

trigger:
  event:
    include:
      - pull_request

steps:
  - name: up
    commands:
      - docker-compose -f docker-compose.drone.yml up -d --build --force-recreate

  - name: test
    commands:
      - docker-compose -f docker-compose.drone.yml exec -T photoprism make all test install migrate

  - name: down
    commands:
      - docker-compose -f docker-compose.drone.yml down
    when:
      status:
        - failure
        - success

---
kind: pipeline
type: exec
name: linux-arm64

trigger:
  branch:
    - master
    - release

platform:
  arch: arm64
  os: linux

steps:
  - name: deploy-preview
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - scripts/docker-login.sh
      - make docker-photoprism-arm64-preview
    when:
      branch:
        - master

  - name: deploy-release
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - scripts/docker-login.sh
      - make docker-photoprism-arm64
    when:
      branch:
        - release

  - name: clean
    commands:
      - docker system prune -f
    when:
      status:
        - success
---
kind: signature
hmac: 4348a3416fe1ae3bd56f07e92266ef87c865bd8a3438c3a6d7f2cc6fcd8baf63

...
