## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION   ##
## Setup: https://docs.photoprism.app/developer-guide/setup/ ##

services:
  ## MySQL 8 Database Server
  ## Docs: https://dev.mysql.com/doc/refman/8.0/en/
  mysql:
    image: mysql:8
    command: --port=4001 --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    expose:
      - "4001" # database port (internal)
    environment:
      MYSQL_DATABASE: "photoprism"
      MYSQL_USER: "photoprism"
      MYSQL_PASSWORD: "photoprism"
      MYSQL_ROOT_PASSWORD: "photoprism"

## Join shared "photoprism-develop" network
networks:
  default:
    name: photoprism-develop
    external: true
