package commands

import (
	"fmt"
	"slices"
	"strings"

	"github.com/urfave/cli/v2"

	"github.com/photoprism/photoprism/internal/ai/vision"
	"github.com/photoprism/photoprism/internal/config"
	"github.com/photoprism/photoprism/internal/workers"
	"github.com/photoprism/photoprism/pkg/txt"
)

// VisionResetCommand configures the command name, flags, and action.
var VisionResetCommand = &cli.Command{
	Name:      "reset",
	Usage:     "Resets data generated by computer vision models for pictures that match the specified search filters",
	ArgsUsage: "[filter]...",
	Flags: []cli.Flag{
		&cli.StringFlag{
			Name:    "models",
			Aliases: []string{"m"},
			Usage:   "computer vision `MODELS` to reset, e.g. caption or labels",
			Value:   "",
		},
		PicturesCountFlag(),
		VisionSourceFlag(vision.DefaultSrc),
		YesFlag(),
	},
	Action: visionResetAction,
}

// visionResetAction removes the captions and labels the selected models generated for the pictures
// that match the search filters.
func visionResetAction(ctx *cli.Context) error {
	return CallWithDependencies(ctx, func(conf *config.Config) error {
		models := vision.ParseModelTypes(ctx.String("models"))
		resetCaptions := slices.Contains(models, vision.ModelTypeCaption)
		resetLabels := slices.Contains(models, vision.ModelTypeLabels)

		if !resetCaptions && !resetLabels {
			log.Warn("vision: no resettable models were specified, nothing to reset")
			return nil
		}

		selectedModels := make([]string, 0, 2)

		if resetCaptions {
			selectedModels = append(selectedModels, vision.ModelTypeCaption)
		}
		if resetLabels {
			selectedModels = append(selectedModels, vision.ModelTypeLabels)
		}

		source, err := sanitizeVisionSource(ctx.String("source"))

		if err != nil {
			return cli.Exit(err.Error(), 1)
		}

		label := fmt.Sprintf("Reset generated %s for matching pictures?", txt.JoinAnd(selectedModels))

		if proceed, confirmErr := ConfirmAction(ctx.Bool("yes"), label); confirmErr != nil {
			return confirmErr
		} else if !proceed {
			log.Infof("vision: kept the generated %s", txt.JoinAnd(selectedModels))
			return nil
		}

		worker := workers.NewVision(conf)
		filter := strings.TrimSpace(strings.Join(ctx.Args().Slice(), " "))

		return worker.Reset(
			filter,
			ctx.Int("count"),
			selectedModels,
			string(source),
		)
	})
}
