package commands

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/photoprism/photoprism/internal/ai/vision"
	"github.com/photoprism/photoprism/internal/photoprism/get"
	"github.com/photoprism/photoprism/pkg/fs"
)

// withVisionYaml points the test config at a "vision.yml" with the specified content and gives
// the command a fresh vision configuration to load it into, restoring both afterwards.
func withVisionYaml(t *testing.T, content string) {
	t.Helper()

	fileName := filepath.Join(t.TempDir(), "vision.yml")
	require.NoError(t, os.WriteFile(fileName, []byte(content), fs.ModeFile))

	conf := get.Config()
	visionYaml, visionConfig := conf.Options().VisionYaml, vision.Config

	t.Cleanup(func() {
		conf.Options().VisionYaml = visionYaml
		vision.Config = visionConfig
	})

	conf.Options().VisionYaml = fileName
	vision.Config = vision.NewConfig()
}

// remoteLabelsVisionYaml selects a labels model served by Ollama.
const remoteLabelsVisionYaml = `Models:
- Type: labels
  Engine: ollama
  Name: qwen3-vl:4b-instruct
`

func TestVisionStatusCommand(t *testing.T) {
	t.Run("Table", func(t *testing.T) {
		output, err := RunWithTestContext(VisionStatusCommand, []string{"status"})
		require.NoError(t, err)

		// The status lines go above the tables and cover every feature.
		assert.Contains(t, output, "NSFW")
		assert.Contains(t, output, "Captions")
		assert.Contains(t, output, "GLOBAL OPTIONS")
		assert.Contains(t, output, "LABELS")
		assert.Contains(t, output, "NSFW DETECTION")
		assert.Contains(t, output, "onnx-provider")
		assert.Contains(t, output, "labels-model")
		assert.Contains(t, output, "nsfw-model")
		assert.Contains(t, output, "Thresholds.NSFWUpload")

		// Unrelated options must not leak into the focused report.
		assert.NotContains(t, output, "originals-path")
		assert.NotContains(t, output, "face-cluster-dist")
	})
	t.Run("VisionYaml", func(t *testing.T) {
		withVisionYaml(t, remoteLabelsVisionYaml)
		output, err := RunWithTestContext(VisionStatusCommand, []string{"status"})
		require.NoError(t, err)
		assert.Contains(t, output, "Labels are generated by qwen3-vl:4b-instruct through ollama after indexing and on schedule.")
		assert.Contains(t, output, "auto (qwen3-vl:4b-instruct)")
	})
	t.Run("VisionUri", func(t *testing.T) {
		conf := get.Config()
		visionUri := conf.Options().VisionUri

		t.Cleanup(func() {
			conf.Options().VisionUri = visionUri
			conf.PropagateVision()
		})

		conf.Options().VisionUri = "https://vision.example.com/api/v1/vision"
		output, err := RunWithTestContext(VisionStatusCommand, []string{"status"})
		require.NoError(t, err)
		assert.Contains(t, output, "through vision")
	})
	t.Run("JSON", func(t *testing.T) {
		output, err := RunWithTestContext(VisionStatusCommand, []string{"status", "--json"})
		require.NoError(t, err)

		var payload struct {
			Status   []string `json:"status"`
			Sections []struct {
				Title string              `json:"title"`
				Items []map[string]string `json:"items"`
			} `json:"sections"`
		}

		require.NoError(t, json.Unmarshal([]byte(output), &payload))
		assert.GreaterOrEqual(t, len(payload.Status), 4)
		require.Len(t, payload.Sections, 3)
		assert.Equal(t, "Global Options", payload.Sections[0].Title)
		assert.Equal(t, "Labels", payload.Sections[1].Title)
		assert.Equal(t, "NSFW Detection", payload.Sections[2].Title)
	})
}

// TestVisionStatusCommandAlias checks that the command also answers to "config", like "faces status".
func TestVisionStatusCommandAlias(t *testing.T) {
	assert.Equal(t, "status", VisionStatusCommand.Name)
	assert.Contains(t, VisionStatusCommand.Aliases, "config")
	assert.Contains(t, VisionCommands.Subcommands, VisionStatusCommand)
}
