package entity

// CameraMakes maps internal make identifiers to normalized names.
var CameraMakes = map[string]string{
	"acer":                        "Acer",
	"ACER":                        "Acer",
	"asus":                        "ASUS",
	"Asus":                        "ASUS",
	"ASUS_AI2302":                 "ASUS",
	"apple":                       "Apple",
	"Casio":                       "CASIO",
	"CASIO COMPUTER":              "CASIO",
	"CASIO COMPUTER CO":           "CASIO",
	"CASIO COMPUTER CO.":          "CASIO",
	"CASIO COMPUTER CO.,LTD":      "CASIO",
	"CASIO COMPUTER CO.,LTD.":     "CASIO",
	"CASIO CORPORATION":           "CASIO",
	"Fujifilm":                    "FUJIFILM",
	"FUJIFILM CORPORATION":        "FUJIFILM",
	"Garmin-Asus":                 "Garmin",
	"google":                      "Google",
	"GOOGLE":                      "Google",
	"U63667E4U111368":             "Google",
	"Hewlett-Packard":             "HP",
	"htc":                         "HTC",
	"Kodak":                       "KODAK",
	"EASTMAN KODAK":               "KODAK",
	"EASTMAN KODAK COMPANY":       "KODAK",
	"Leica Camera AG":             "Leica",
	"LEICA":                       "Leica",
	"LG Electronics":              "LG",
	"LGE":                         "LG",
	"lge":                         "LG",
	"Minolta Co., Ltd.":           "Minolta",
	"MINOLTA CO.,LTD":             "Minolta",
	"KONICA MINOLTA":              "Konica Minolta",
	"Motorol":                     "Motorola",
	"Motorola Mobility":           "Motorola",
	"motorola":                    "Motorola",
	"samsung":                     "Samsung",
	"SAMSUNG":                     "Samsung",
	"Samsung Electronics":         "Samsung",
	"SAMSUNG TECHWIN Co.":         "Samsung",
	"SAMSUNG TECHWIN":             "Samsung",
	"Samsung Techwin":             "Samsung",
	"sharp":                       "SHARP",
	"Sharp":                       "SHARP",
	"sigma":                       "SIGMA",
	"Sigma":                       "SIGMA",
	"OLYMPUS":                     "Olympus",
	"OLYMPUS CORPORATION":         "Olympus",
	"OLYMPUS DIGITAL CAMERA":      "Olympus",
	"OLYMPUS IMAGING CORP.":       "Olympus",
	"OLYMPUS OPTICAL CO.,LTD":     "Olympus",
	"ONEPLUS":                     "OnePlus",
	"Nikon":                       "NIKON",
	"NIKON CORPORATION":           "NIKON",
	"Huawei":                      "HUAWEI",
	"RaspberryPi":                 "Raspberry Pi",
	"RICOH IMAGING COMPANY, LTD.": "RICOH",
	"Ricoh":                       "RICOH",
	"Pentax":                      "PENTAX",
	"PENTAX Corporation":          "PENTAX",
	"PENTAX CORPORATION":          "PENTAX",
	"Blackberry":                  "BlackBerry",
	"Research In Motion":          "BlackBerry",
	"Sony":                        "SONY",
	"VenTrade GmbH, Germany":      "VenTrade",
}
