package entity

import (
	"crypto/sha1" //nolint:gosec // G505: Stable non-cryptographic face identifier hash.
	"encoding/base32"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/jinzhu/gorm"

	"github.com/photoprism/photoprism/internal/ai/face"
	"github.com/photoprism/photoprism/pkg/clean"
	"github.com/photoprism/photoprism/pkg/dsn"
	"github.com/photoprism/photoprism/pkg/rnd"
)

var faceMutex = sync.Mutex{}

// UpdateFaces reports whether a matching pass changed a cluster, so callers know to refresh.
var UpdateFaces = atomic.Bool{}

// Face represents the face of a Subject.
type Face struct {
	ID              string          `gorm:"type:VARBINARY(64);primary_key;auto_increment:false;" json:"ID" yaml:"ID"`
	FaceSrc         string          `gorm:"type:VARBINARY(8);" json:"Src" yaml:"Src,omitempty"`
	FaceKind        int             `json:"Kind" yaml:"Kind,omitempty"`
	FaceHidden      bool            `json:"Hidden" yaml:"Hidden,omitempty"`
	SubjUID         string          `gorm:"type:VARBINARY(42);index;default:'';" json:"SubjUID" yaml:"SubjUID,omitempty"`
	Samples         int             `json:"Samples" yaml:"Samples,omitempty"`
	SampleRadius    float64         `json:"SampleRadius" yaml:"SampleRadius,omitempty"`
	Collisions      int             `json:"Collisions" yaml:"Collisions,omitempty"`
	CollisionRadius float64         `json:"CollisionRadius" yaml:"CollisionRadius,omitempty"`
	MergeRetry      uint8           `gorm:"type:TINYINT(3);default:0" json:"-" yaml:"-"`
	MergeNotes      string          `gorm:"type:VARCHAR(255);default:'';" json:"-" yaml:"-"`
	EmbedModel      string          `gorm:"column:embed_model;type:VARBINARY(32);index;default:'';" json:"-" yaml:"EmbedModel,omitempty"`
	EmbeddingJSON   json.RawMessage `gorm:"type:MEDIUMBLOB;" json:"-" yaml:"EmbeddingJSON,omitempty"`
	embedding       face.Embedding  `gorm:"-" yaml:"-"`
	// reopened records that this cluster changed after a run read it, so a caller about to stamp
	// it as matched can tell it apart from one that merely started out unmatched - which is the
	// only state the timestamp itself can report, since both are NULL.
	reopened  bool       `gorm:"-" yaml:"-"`
	MatchedAt *time.Time `json:"MatchedAt" yaml:"MatchedAt,omitempty"`
	CreatedAt time.Time  `json:"CreatedAt" yaml:"CreatedAt,omitempty"`
	UpdatedAt time.Time  `json:"UpdatedAt" yaml:"UpdatedAt,omitempty"`
}

// Faceless can be used as argument to match unmatched face markers.
var Faceless = []string{""}

// TableName returns the entity table name.
func (Face) TableName() string {
	return "faces"
}

// NewFace returns a new face for embeddings produced by the specified model.
func NewFace(subjUID, faceSrc string, embeddings face.Embeddings, model face.ModelName) *Face {
	result := &Face{
		SubjUID: subjUID,
		FaceSrc: faceSrc,
	}

	if err := result.SetEmbeddings(embeddings, model); err != nil {
		log.Errorf("face: failed setting embeddings (%s)", err)
	}

	return result
}

// MatchId returns a compound id for matching.
func (m *Face) MatchId(f Face) string {
	if m.ID == "" || f.ID == "" {
		return ""
	}

	if m.ID < f.ID {
		return fmt.Sprintf("%s-%s", m.ID, f.ID)
	} else {
		return fmt.Sprintf("%s-%s", f.ID, m.ID)
	}
}

// SkipMatching checks whether the face should be skipped when matching.
// Only ResolveCollision still raises the kind, to AmbiguousFace.
func (m *Face) SkipMatching() bool {
	return m.FaceKind > 1
}

// SetEmbeddings assigns face embeddings produced by the specified model. The model is
// recorded as passed, so a cluster built from stored vectors keeps their provenance
// instead of adopting whichever model happens to be configured now.
func (m *Face) SetEmbeddings(embeddings face.Embeddings, model face.ModelName) (err error) {
	if len(embeddings) == 0 {
		return fmt.Errorf("invalid embedding")
	}

	// Comparing this cluster with anything the configured model produces would mix two
	// embedding spaces, so it is refused where the row is built rather than where it is read.
	if !face.ModelsComparable(model, face.EmbeddingModelName()) {
		return fmt.Errorf("embedding model %s cannot be compared with %s", clean.Log(model), clean.Log(face.EmbeddingModelName()))
	}

	m.embedding, m.SampleRadius, m.Samples = face.EmbeddingsMidpoint(embeddings)

	// The expected length depends on the configured model, so vectors generated by a
	// different one are rejected rather than mixed into an incompatible vector space.
	// Optimize and merge runs hit this for every legacy cluster after a model switch,
	// so the message has to name the way out.
	if dims := face.ExpectedDims(); len(m.embedding) != dims {
		if current := face.EmbeddingModelName(); current != "" {
			return fmt.Errorf("embedding has %d values, expected %d for model %s, run photoprism faces migrate to regenerate", len(m.embedding), dims, clean.Log(current))
		}

		return fmt.Errorf("embedding has %d values, expected %d", len(m.embedding), dims)
	}

	m.EmbedModel = model

	// A midpoint with no magnitude describes no face and sits one unit from every unit vector, so
	// a cluster built from it would accept whatever a model reaching past 1 compares with it.
	// Refused here as well as in Match, so such a row cannot be stored in the first place - which
	// is also what keeps the recorded kind and the migration predicate in agreement.
	if m.embedding.Zero() {
		return fmt.Errorf("embedding has no magnitude")
	}

	// Classified from the midpoint that is stored, not from the inputs it was computed over: two
	// opposite vectors are each regular while their mean is not a face. Recorded rather than left
	// at zero because the "face:N" search filter reads the number, and raised rather than assigned
	// so a cluster already reported as ambiguous is not downgraded.
	if k := int(m.embedding.Kind()); k > m.FaceKind {
		m.FaceKind = k
	}

	// Limit sample radius to reduce false positives.
	m.SampleRadius = face.ClampSampleRadius(m.SampleRadius)

	// An extent of zero is unmeasurable rather than tight, and would leave the cluster narrower than
	// any real pair of one person's faces. Duplicate samples reach this only when rounding in the
	// mean leaves the extent exactly zero, which 2 and 4 copies do and 3 and 5 do not, so the reach
	// of a duplicate cluster follows its member count rather than a decision anyone made.
	if m.SampleRadius <= 0 {
		m.SampleRadius = face.ClusterRadius
	}

	m.EmbeddingJSON, err = json.Marshal(m.embedding)

	if err != nil {
		return err
	}

	//nolint:gosec // G401: Stable identifier hash; not used for security decisions.
	s := sha1.Sum(m.EmbeddingJSON)

	// Update Face ID and reset match timestamp,
	m.ID = base32.StdEncoding.EncodeToString(s[:])

	m.reopen()

	return nil
}

// Reopened reports whether this cluster changed after the run read it, and therefore has to be
// compared against the markers again rather than stamped as matched.
func (m *Face) Reopened() bool {
	return m != nil && m.reopened
}

// reopen clears the match timestamp and records that this cluster needs comparing again.
func (m *Face) reopen() {
	m.MatchedAt = nil
	m.reopened = true
}

// Matched updates the match timestamp.
func (m *Face) Matched() error {
	m.MatchedAt = TimeStamp()
	return UnscopedDb().Model(m).UpdateColumns(Values{"matched_at": m.MatchedAt}).Error
}

// Embedding returns parsed face embedding.
func (m *Face) Embedding() face.Embedding {
	if len(m.EmbeddingJSON) == 0 {
		return face.Embedding{}
	} else if len(m.embedding) > 0 {
		return m.embedding
	} else if err := json.Unmarshal(m.EmbeddingJSON, &m.embedding); err != nil {
		log.Errorf("failed parsing face embedding json: %s", err)
	}

	return m.embedding
}

// SameEmbeddingModel reports whether the stored embedding can be compared with newly
// generated vectors. Legacy rows without provenance are compatible with FaceNet only.
func (m *Face) SameEmbeddingModel() bool {
	return face.ModelsComparable(m.EmbedModel, face.EmbeddingModelName())
}

// AcceptDist returns the distance below which an embedding joins this cluster.
// The stored radius is clamped on read as well as on write, so a changed cluster
// radius applies to existing rows before a match run rewrites their statistics.
func (m *Face) AcceptDist() float64 {
	return face.AcceptDist(m.SampleRadius)
}

// Match tests if embeddings produced by the specified model match this face.
func (m *Face) Match(embeddings face.Embeddings, model face.ModelName) (match bool, dist float64) {
	dist = -1

	if embeddings.Empty() {
		// No embeddings, no match.
		return false, dist
	}

	// Two models can produce vectors of the same length that mean entirely different
	// things, so provenance decides comparability before any distance is calculated.
	// Both sides are checked: the argument carries its own model, not this cluster's.
	if !m.SameEmbeddingModel() || !face.SameEmbeddingSpace(m.EmbedModel, model) {
		return false, dist
	}

	faceEmbedding := m.Embedding()

	// A cluster with no magnitude is 1 away from every unit embedding, so it accepts whatever a
	// model reaching past 1 compares with it. Refused here as well as where vectors are written,
	// because a row may predate that check.
	if len(faceEmbedding) == 0 || faceEmbedding.Zero() {
		return false, dist
	}

	// Calculate the smallest distance to embeddings.
	dist = embeddings.Dist(faceEmbedding)

	// Any reasons embeddings do not match this face?
	switch {
	case dist < 0:
		// Should never happen.
		return false, dist
	case dist > m.AcceptDist():
		// Too far.
		return false, dist
	case m.CollisionRadius > face.CollisionDist && dist > m.CollisionRadius:
		// Within radius of reported collisions.
		return false, dist
	}

	// If not, at least one of the embeddings match!
	return true, dist
}

// Mergeable reports whether one midpoint can stand for this cluster and the given one, and returns
// the distance between them.
//
// Bounded by ClusterDist rather than by Match, which reads this cluster's own extent and collision
// radius and so answers differently depending on which of the two is asked.
func (m *Face) Mergeable(f *Face) (mergeable bool, dist float64) {
	dist = -1

	// An id on both sides, or the verdict would depend on the direction asked.
	if m == nil || f == nil || m.ID == "" || f.ID == "" || m.ID == f.ID {
		return false, dist
	}

	// Averaging vectors from two models yields a midpoint that describes neither.
	if !face.SameEmbeddingSpace(m.EmbedModel, f.EmbedModel) {
		return false, dist
	}

	a, b := m.Embedding(), f.Embedding()

	// Refused as in Match: such a midpoint is one unit from every unit vector.
	if len(a) == 0 || len(b) == 0 || a.Zero() || b.Zero() {
		return false, dist
	}

	dist = a.Dist(b)

	return dist >= 0 && dist <= face.ClusterDist, dist
}

// ResolveCollision resolves a collision with a different subject's face.
func (m *Face) ResolveCollision(embeddings face.Embeddings, model face.ModelName) (resolved bool, err error) {
	if m.SubjUID == "" {
		// Ignore reports for anonymous faces.
		return false, nil
	} else if m.ID == "" {
		return false, fmt.Errorf("invalid face id")
	} else if len(m.EmbeddingJSON) == 0 {
		return false, fmt.Errorf("embedding must not be empty")
	}

	if match, dist := m.Match(embeddings, model); !match {
		// Embeddings don't match this face. Ignore.
		return false, nil
	} else if dist < 0 {
		// Should never happen.
		return false, fmt.Errorf("collision distance must be positive")
	} else if dist < face.AmbiguityDist() {
		log.Warnf("faces: %s has ambiguous subject %s with a similar face at dist %f with source %s", m.ID, SubjNames.Log(m.SubjUID), dist, SrcString(m.FaceSrc))

		m.FaceKind = int(face.AmbiguousFace)
		m.UpdatedAt = Now()
		m.MatchedAt = &m.UpdatedAt
		m.Collisions++
		m.CollisionRadius = dist
		UpdateFaces.Store(true)
		return true, m.Updates(Values{"collisions": m.Collisions, "collision_radius": m.CollisionRadius,
			"face_kind": m.FaceKind, "updated_at": m.UpdatedAt, "matched_at": m.MatchedAt})
	} else {
		// Reopened rather than merely cleared: this narrows the cluster mid-run, and the markers
		// ReviseMatches drops below have nothing to be rematched against if the run then stamps
		// it as matched on its way out.
		m.reopen()
		m.Collisions++
		m.CollisionRadius = dist - face.Epsilon
		UpdateFaces.Store(true)
	}

	err = m.Updates(Values{"collisions": m.Collisions, "collision_radius": m.CollisionRadius, "matched_at": m.MatchedAt})

	if err != nil {
		return true, err
	}

	if revised, err := m.ReviseMatches(); err != nil {
		return true, err
	} else if r := len(revised); r > 0 {
		log.Infof("faces: resolved %d conflicts", r)
	}

	return true, nil
}

// InheritCollision narrows this cluster to the tightest collision bound its sources recorded.
//
// NewFace sets none, so a merged row would otherwise start unbounded and re-earn its narrowing.
// Only ever tightens, since FirstOrCreateFace may return a row already carrying one.
func (m *Face) InheritCollision(from Faces) error {
	radius, collisions := from.CollisionBound(m.SampleRadius)

	if radius == 0 || m.CollisionRadius > face.CollisionDist && m.CollisionRadius <= radius {
		return nil
	}

	m.Collisions, m.CollisionRadius = collisions, radius

	return m.Updates(Values{"collisions": m.Collisions, "collision_radius": m.CollisionRadius})
}

// ClearCollision discards a recorded collision, so the cluster matches at its full accept distance.
//
// A collision records that two subjects competed for the same embeddings. Once an operator states
// they are one person the premise is gone, and the narrowing gates the cluster against faces it
// should hold; a later pass re-derives a collision that is still real.
func (m *Face) ClearCollision() error {
	if m.ID == "" {
		return fmt.Errorf("invalid face id")
	} else if !m.HasCollision() {
		return nil
	}

	m.Collisions = 0
	m.CollisionRadius = 0

	// Reopened so the markers this cluster refused while narrowed are compared against it again;
	// leaving the stamp would keep them out until something else reopened it.
	m.reopen()
	UpdateFaces.Store(true)

	values := Values{"collisions": m.Collisions, "collision_radius": m.CollisionRadius, "matched_at": m.MatchedAt}

	// Only ResolveCollision raises the kind, so a cluster carrying the ambiguous kind was marked by
	// that path and returns to the regular one every cluster is created with. Any other kind is
	// left alone.
	if m.FaceKind == int(face.AmbiguousFace) {
		m.FaceKind = int(face.RegularFace)
		values["face_kind"] = m.FaceKind
	}

	return m.Updates(values)
}

// HasCollision reports whether a narrowing collision is recorded for this cluster.
func (m *Face) HasCollision() bool {
	return m != nil && (m.Collisions > 0 || m.CollisionRadius > 0 || m.FaceKind == int(face.AmbiguousFace))
}

// ClearSubjectCollisions discards the collisions recorded for a subject's clusters and reports how
// many were cleared. Used where two subjects turn out to be one person, since every collision
// between their clusters was recorded against an identity that no longer exists.
func ClearSubjectCollisions(subjUID string) (cleared int, err error) {
	if subjUID == "" {
		return 0, fmt.Errorf("subject has no uid")
	}

	var faces Faces

	if err = UnscopedDb().Where("subj_uid = ?", subjUID).
		Where("collisions > 0 OR collision_radius > 0 OR face_kind = ?", int(face.AmbiguousFace)).
		Find(&faces).Error; err != nil {
		return 0, err
	}

	for i := range faces {
		if clearErr := faces[i].ClearCollision(); clearErr != nil {
			return cleared, clearErr
		}

		cleared++
	}

	return cleared, nil
}

// ReviseMatches updates marker matches after face parameters have been changed.
func (m *Face) ReviseMatches() (revised Markers, err error) {
	if m.ID == "" {
		return revised, fmt.Errorf("empty face id")
	}

	var matches Markers

	if err := Db().Where("face_id = ?", m.ID).Where("marker_type = ?", MarkerFace).
		Find(&matches).Error; err != nil {
		log.Debugf("faces: found no matching markers for conflict resolution (%s)", err)
		return revised, err
	} else {
		for _, marker := range matches {
			// A marker from another embedding space cannot be compared with this cluster,
			// so its assignment is left alone rather than dropped on a comparison that
			// never ran.
			if !face.SameEmbeddingSpace(marker.EmbedModel, m.EmbedModel) {
				continue
			}

			if ok, _ := m.Match(marker.Embeddings(), marker.EmbedModel); !ok {
				if updated, err := marker.ClearFace(); err != nil {
					log.Debugf("faces: failed to remove match with marker (%s)", err) // Conflict resolution
					return revised, err
				} else if updated {
					// ClearFace stamps the marker as matched, which is true of the matcher but
					// not of this: the cluster narrowed underneath it and nothing has compared
					// it against the others. Left stamped, it is in neither pass's set and waits
					// for "faces update --force".
					if err = marker.Unmatched(); err != nil {
						log.Debugf("faces: failed to flag marker for rematching (%s)", err)
					}

					revised = append(revised, marker)
				}
			}
		}
	}

	return revised, nil
}

// whereSameEmbeddingSpace restricts a statement to vectors from the specified model's
// embedding space. An empty name selects the legacy rows that predate the provenance
// column, which is deliberate: the model here is a stored cluster's own, never an
// unknown configuration.
func whereSameEmbeddingSpace(stmt *gorm.DB, model face.ModelName) *gorm.DB {
	switch model {
	case "", face.ModelFaceNet:
		// A vector with no recorded model is FaceNet's, so the two are one space in both
		// directions - which is what face.SameEmbeddingSpace reports and ReviseMatches applies
		// to these same rows. Selecting only the blank ones would leave a legacy cluster unable
		// to attract the markers a loaded embedder has since stamped.
		return stmt.Where("embed_model IN (?)", []string{face.ModelFaceNet, ""})
	default:
		return stmt.Where("embed_model = ?", model)
	}
}

// MatchMarkers finds and references matching markers.
//
// Only the detection floor admits a marker, not the clustering one: the second pass marks faces
// a crowd photograph would lose rather than naming people from them. A marker already in a
// cluster is exempt, or the merge path would strand it on one about to be purged.
func (m *Face) MatchMarkers(faceIds []string) error {
	if len(faceIds) == 0 {
		return nil
	}

	var markers Markers

	err := whereSameEmbeddingSpace(Db().
		Where("marker_invalid = 0 AND marker_type = ? AND face_id IN (?)", MarkerFace, faceIds).
		Where("face_id <> '' OR size >= ?", face.SizeThreshold), m.EmbedModel).
		Find(&markers).Error

	if err != nil {
		log.Debugf("faces: failed fetching markers matching face id %s (%s)", strings.Join(faceIds, ", "), err)
		return err
	}

	start := time.Now()
	resultLen := len(markers)

	for i, marker := range markers {
		if time.Since(start) > time.Duration(time.Minute*15) {
			log.Infof("faces: matching %d of %d markers", i, resultLen)
			start = time.Now()
		}
		if ok, dist := m.Match(marker.Embeddings(), marker.EmbedModel); !ok {
			// Ignore.
		} else if _, err = marker.SetFace(m, dist); err != nil {
			return err
		}
	}

	return nil
}

// UpdateMatchStats persists sample statistics from recent matches, only ever widening the extent.
//
// A run visits only the markers that were unmatched when it started, so one face arriving near the
// centroid would otherwise shrink the radius and refuse the members beyond it. SetEmbeddings
// recomputes both from membership, which is the path that may shrink a cluster.
func (m *Face) UpdateMatchStats(samples int, maxDistance float64) error {
	if m.ID == "" || samples <= 0 {
		return nil
	}

	// The epsilon slack is applied before clamping so it can never lift the stored
	// radius above the configured maximum.
	radius := face.ClampSampleRadius(max(maxDistance+face.Epsilon, m.SampleRadius))
	samples = max(samples, m.Samples)

	if m.Samples == samples && m.SampleRadius == radius {
		return nil
	}

	m.Samples = samples
	m.SampleRadius = radius
	UpdateFaces.Store(true)

	return m.Updates(Values{"samples": m.Samples, "sample_radius": m.SampleRadius})
}

// SetMatchStats replaces the sample count and radius with measurements of the cluster's members.
//
// Distinct from UpdateMatchStats, which only ever widens because it sees one pass rather than the
// membership: measuring the whole cluster is what makes a smaller number trustworthy.
func (m *Face) SetMatchStats(samples int, radius float64) error {
	if m.ID == "" || samples <= 0 || radius <= 0 {
		return nil
	}

	radius = face.ClampSampleRadius(radius)

	if m.Samples == samples && m.SampleRadius == radius {
		return nil
	}

	m.Samples, m.SampleRadius = samples, radius
	UpdateFaces.Store(true)

	return m.Updates(Values{"samples": m.Samples, "sample_radius": m.SampleRadius})
}

// SetSubjectUID updates the face's subject uid and related markers.
func (m *Face) SetSubjectUID(subjUid string) (err error) {
	// Update face.
	if err = m.Update("SubjUID", subjUid); err != nil {
		return err
	} else {
		m.SubjUID = subjUid
	}

	UpdateFaces.Store(true)

	// Update related markers.
	if err = Db().Model(&Marker{}).
		Where("face_id = ?", m.ID).
		Where("subj_src = ?", SrcAuto).
		Where("subj_uid <> ?", m.SubjUID).
		Where("marker_invalid = 0").
		UpdateColumns(Values{"subj_uid": m.SubjUID, "marker_review": false}).Error; err != nil {
		return err
	}

	return m.RefreshPhotos()
}

// RefreshPhotos flags related photos for metadata maintenance.
func (m *Face) RefreshPhotos() error {
	if m.ID == "" {
		return fmt.Errorf("empty face id")
	}

	UpdateFaces.Store(true)

	var err error
	switch DbDialect() {
	case dsn.DriverMySQL:
		update := fmt.Sprintf(`UPDATE photos p JOIN files f ON f.photo_id = p.id JOIN %s m ON m.file_uid = f.file_uid
			SET p.checked_at = NULL WHERE m.face_id = ?`, Marker{}.TableName())
		err = UnscopedDb().Exec(update, m.ID).Error
	default:
		update := fmt.Sprintf(`UPDATE photos SET checked_at = NULL WHERE id IN (SELECT f.photo_id FROM files f
			JOIN %s m ON m.file_uid = f.file_uid WHERE m.face_id = ?)`, Marker{}.TableName())
		err = UnscopedDb().Exec(update, m.ID).Error
	}

	return err
}

// Hide hides the face by default.
func (m *Face) Hide() (err error) {
	return m.Update("FaceHidden", true)
}

// Show shows the face by default.
func (m *Face) Show() (err error) {
	return m.Update("FaceHidden", false)
}

// Create inserts the face to the database.
func (m *Face) Create() error {
	if m.ID == "" {
		return fmt.Errorf("empty id")
	}

	faceMutex.Lock()
	defer faceMutex.Unlock()

	UpdateFaces.Store(true)

	return Db().Create(m).Error
}

// Delete removes the face from the database.
func (m *Face) Delete() error {
	if m.ID == "" {
		return fmt.Errorf("empty id")
	}

	UpdateFaces.Store(true)

	// Remove face id from markers before deleting.
	if err := Db().Model(&Marker{}).
		Where("face_id = ?", m.ID).
		UpdateColumns(Values{"face_id": "", "face_dist": -1}).Error; err != nil {
		return err
	}

	return Db().Delete(m).Error
}

// Update a face property in the database.
func (m *Face) Update(attr string, value any) error {
	if m.ID == "" {
		return fmt.Errorf("empty id")
	}

	UpdateFaces.Store(true)

	return UnscopedDb().Model(m).Update(attr, value).Error
}

// Updates face properties in the database.
func (m *Face) Updates(values any) error {
	if m.ID == "" {
		return fmt.Errorf("empty id")
	}

	UpdateFaces.Store(true)

	return UnscopedDb().Model(m).Updates(values).Error
}

// FirstOrCreateFace returns the existing entity, inserts a new entity or nil in case of errors.
func FirstOrCreateFace(m *Face) *Face {
	if m == nil {
		return nil
	}

	if m.ID == "" {
		return nil
	}

	result := Face{}

	// Search existing face with the same ID. Report if found and it belongs to another person.
	if findErr := UnscopedDb().Where("id = ?", m.ID).First(&result).Error; findErr == nil && result.ID != "" {
		if m.SubjUID != result.SubjUID {
			log.Warnf("faces: %s has ambiguous subjects %s and %s", m.ID, SubjNames.Log(m.SubjUID), SubjNames.Log(result.SubjUID))
		}
		return &result
	} else if err := m.Create(); err == nil {
		UpdateFaces.Store(true)
		return m
	} else if findErr = UnscopedDb().Where("id = ?", m.ID).First(&result).Error; findErr == nil && result.ID != "" {
		if m.SubjUID != result.SubjUID {
			log.Warnf("faces: %s has ambiguous subjects %s and %s", m.ID, SubjNames.Log(m.SubjUID), SubjNames.Log(result.SubjUID))
		}
		return &result
	} else {
		log.Errorf("faces: failed to add %s (%s)", m.ID, err)
	}

	return nil
}

// FindFace returns an existing entity if exists.
func FindFace(id string) *Face {
	if id == "" {
		return nil
	}

	f := Face{}

	if err := Db().Where("id = ?", strings.ToUpper(id)).First(&f).Error; err != nil {
		return nil
	}

	return &f
}

// ValidFaceCount counts the number of valid face markers for a file uid.
func ValidFaceCount(fileUid string) (c int) {
	if !rnd.IsUID(fileUid, FileUID) {
		return
	}

	if err := Db().Model(Marker{}).
		Where("file_uid = ? AND marker_type = ?", fileUid, MarkerFace).
		Where("marker_invalid = 0").
		Count(&c).Error; err != nil {
		log.Errorf("file: %s (count faces)", err)
		return 0
	} else {
		return c
	}
}
