# PhotoPrism does not use the AF_ALG userspace crypto interface, so the algif_aead
# module is prevented from loading. Remove this file if you need AF_ALG on this server.
install algif_aead /bin/false
