package cluster

// Default values used by cluster provisioning helpers.
const (
	// DefaultDatabaseProvisionPrefix is applied to auto-provisioned database names and user accounts.
	DefaultDatabaseProvisionPrefix = "cluster_"
	// DatabaseProvisionPrefixMaxLen keeps generated usernames within the MySQL 32 character budget.
	DatabaseProvisionPrefixMaxLen = 20
)

// Example values used by documentation and tests to illustrate cluster tokens.
const (
	// ExampleJoinToken represents a valid portal join token. Sample only.
	ExampleJoinToken = "pGVplw8-eISgkdQN-Mep62nQ" //nolint:gosec // example value, not a secret
	// ExampleJoinTokenAlt provides an alternative join token for negative/rotation tests. Sample only.
	ExampleJoinTokenAlt = "k9sEFe6-A7gt6zqm-gY9gFh0" //nolint:gosec // example value, not a secret
	// ExampleClientID is a sample node client identifier issued by the portal.
	ExampleClientID = "cs5gfen1bgxz7s9i"
	// ExampleClientSecret is a sample node client secret matching the format generated by rnd.ClientSecret().
	ExampleClientSecret = "A1B2C3D4E5F6G7H8J9K0L1M2N3P4Q5R6" //nolint:gosec // example value
)
