package fs

// TypeMap maps file types to a representative extension string.
type TypeMap map[Type]string

// TypeInfo contains human-readable descriptions for supported file formats
var TypeInfo = TypeMap{
	ArchiveZip:      "ZIP Archive File",
	DocumentPDF:     "Portable Document Format (PDF)",
	ImageJpeg:       "Joint Photographic Experts Group (JPEG)",
	ImageJpegXL:     "JPEG XL",
	ImageThumb:      "Thumbnail Image",
	ImagePng:        "Portable Network Graphics",
	ImageGif:        "Graphics Interchange Format",
	ImageTiff:       "Tag Image File Format",
	ImagePsd:        "Adobe Photoshop",
	ImageBmp:        "Bitmap",
	ImageMPO:        "Stereoscopic JPEG (3D)",
	ImageAvif:       "AV1 Image File Format",
	ImageAvifS:      "AV1 Image Sequence",
	ImageHeif:       "High Efficiency Image File Format",
	ImageHeic:       "High Efficiency Image Container",
	ImageHeicS:      "HEIC Image Sequence",
	ImageWebp:       "Google WebP",
	ImageDng:        "Adobe Digital Negative",
	ImageRaw:        "Unprocessed Sensor Data",
	VectorSVG:       "Scalable Vector Graphics",
	VectorAI:        "Adobe Illustrator",
	VectorPS:        "Adobe PostScript",
	VectorEPS:       "Encapsulated PostScript",
	VideoWebm:       "Google WebM",
	VideoMp2:        "MPEG 2 (H.262)",
	VideoAvc:        "Advanced Video Coding (H.264, MPEG-4 Part 10)",
	VideoHvc:        "High Efficiency Video Coding (H.265)",
	VideoHev:        "High Efficiency Video Coding (HEVC) Bitstream",
	VideoVvc:        "Versatile Video Coding (H.266)",
	VideoEvc:        "Essential Video Coding (MPEG-5 Part 1)",
	VideoAv1:        "AOMedia Video 1",
	VideoVp8:        "Google VP8 Video",
	VideoVp9:        "Google VP9 Video",
	VideoMov:        "Apple QuickTime",
	VideoMp4:        "Multimedia Container (MPEG-4 Part 14)",
	VideoM4v:        "Apple iTunes Multimedia Container",
	VideoMXF:        "Material Exchange Format",
	VideoAVI:        "Microsoft Audio Video Interleave",
	VideoASF:        "Advanced Systems Format ",
	VideoWMV:        "Windows Media",
	VideoDV:         "DV Video",
	Video3GP:        "Mobile Multimedia Container (3G)",
	Video3G2:        "Mobile Multimedia Container (CDMA2000)",
	VideoFlash:      "Adobe Flash",
	VideoMkv:        "Matroska Multimedia Container",
	VideoMpeg:       "Moving Picture Experts Group (MPEG)",
	VideoMjpeg:      "Motion JPEG",
	VideoM2TS:       "MPEG-2 Transport Stream (M2TS)",
	VideoAVCHD:      "Advanced Video Coding High Definition (AVCHD)",
	VideoTheora:     "Ogg Media (OGG)",
	SidecarXMP:      "Adobe Extensible Metadata Platform",
	SidecarAppleXml: "Apple Image Edits XML",
	SidecarXml:      "Extensible Markup Language",
	SidecarJson:     "Serialized JSON Data (Exiftool, Google Photos)",
	SidecarYaml:     "Serialized YAML Data (Config, Metadata)",
	SidecarText:     "Plain Text",
	SidecarInfo:     "Info Text",
	SidecarMarkdown: "Markdown Formatted Text",
	TypeUnknown:     "Other",
}
