package migrate

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// dialectNames maps the dialect names used in generated identifiers to the description of their databases.
var dialectNames = map[string]string{
	"MySQL":   "MySQL and MariaDB",
	"SQLite3": "SQLite",
}

// DialectSource reads the migrations of a dialect from the SQL files in dir, sorted by filename.
// A file named <id>.sql runs in the main stage, and <id>.<stage>.sql in the given stage.
func DialectSource(dir, dialect string) (result Migrations, err error) {
	files, err := os.ReadDir(dir)

	if err != nil {
		return nil, err
	}

	for _, file := range files {
		if file.IsDir() {
			continue
		}

		parts := strings.Split(file.Name(), ".")
		stage := StageMain

		switch {
		case len(parts) == 2 && parts[0] != "" && parts[1] == "sql":
		case len(parts) == 3 && parts[0] != "" && parts[1] != "" && parts[2] == "sql":
			stage = parts[1]
		default:
			return nil, fmt.Errorf("invalid migration filename %s", file.Name())
		}

		s, readErr := os.ReadFile(filepath.Join(dir, file.Name())) //nolint:gosec // G304: names come from listing the source directory

		if readErr != nil {
			return nil, readErr
		} else if len(bytes.TrimSpace(s)) == 0 {
			return nil, fmt.Errorf("migration %s is empty", file.Name())
		}

		result = append(result, Migration{ID: parts[0], Dialect: dialect, Stage: stage, Statements: splitStatements(s)})
	}

	return result, nil
}

// splitStatements splits SQL into statements that each end with a semicolon.
func splitStatements(b []byte) []string {
	stmts := bytes.Split(b, []byte(";\n"))
	result := make([]string, 0, len(stmts))

	for i := range stmts {
		if s := bytes.TrimSpace(stmts[i]); len(s) > 0 {
			if s[len(s)-1] != ';' {
				s = append(s, ';')
			}

			result = append(result, string(s))
		}
	}

	return result
}

// DialectCode returns the formatted Go source that declares the migrations of a dialect.
func DialectCode(name string, migrations Migrations) ([]byte, error) {
	description, ok := dialectNames[name]

	if !ok {
		return nil, fmt.Errorf("unknown dialect %s", name)
	}

	var buf bytes.Buffer

	if err := dialectTemplate.Execute(&buf, struct {
		Name        string
		Description string
		Migrations  Migrations
	}{
		Name:        name,
		Description: description,
		Migrations:  migrations,
	}); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}

// dialectTemplate renders the generated dialect_<name>.go files.
var dialectTemplate = template.Must(template.New("").Parse(`// Code generated by go generate ./internal/entity/migrate; DO NOT EDIT.

package migrate

// Dialect{{ .Name }} lists the migrations that run on {{ .Description }}.
var Dialect{{ .Name }} = Migrations{
{{- range .Migrations }}
	{
		ID:         {{ printf "%q" .ID }},
		Dialect:    {{ printf "%q" .Dialect }},
		Stage:      {{ printf "%q" .Stage }},
		Statements: []string{ {{ range $index, $s := .Statements }}{{ if $index }}, {{ end }}{{ printf "%q" $s }}{{ end }} },
	},
{{- end }}
}
`))
