package thumb

import (
	"image"
	"math"
)

// Size represents a standard media resolution.
type Size struct {
	Name     Name    `json:"name"`  // Name of the thumbnail size.
	Source   Name    `json:"-"`     // Larger size this size can be generated from.
	Usage    string  `json:"usage"` // Usage example.
	Width    int     `json:"w"`     // Width in pixels.
	Height   int     `json:"h"`     // Height in pixels.
	Public   bool    `json:"-"`     // Size is visible in client applications.
	Fit      bool    `json:"-"`     // Image is fitted to fill this size.
	Optional bool    `json:"-"`     // Size must not be generated by default.
	Required bool    `json:"-"`     // Size must always be generated.
	Options  Options `json:"-"`
}

// Bounds returns the thumb size as image.Rectangle.
func (s Size) Bounds() image.Rectangle {
	return image.Rectangle{Min: image.Point{}, Max: image.Point{X: s.Width, Y: s.Height}}
}

// Fitted returns the pixel dimensions this size renders a source of w x h at. A fit size scales the
// source into its box without ever enlarging it; every other size fills its box exactly. The
// arithmetic mirrors fitImage, so a rendition can be reasoned about without reading it.
func (s Size) Fitted(w, h int) (int, int) {
	if !s.Fit {
		return s.Width, s.Height
	} else if w <= 0 || h <= 0 {
		return 0, 0
	}

	scale := math.Min(float64(s.Width)/float64(w), float64(s.Height)/float64(h))

	if scale >= 1 {
		return w, h
	}

	return maxInt(1, int(float64(w)*scale)), maxInt(1, int(float64(h)*scale))
}

// Uncached tests if thumbnail type exceeds the cached thumbnails size limit.
func (s Size) Uncached() bool {
	return s.Width > SizeCached || s.Height > SizeCached
}

// ExceedsLimit tests if thumbnail type is too large to be delivered, which is a lower bound than
// what may be rendered: MaxRenderSize also covers the source a face crop is rendered from.
func (s Size) ExceedsLimit() bool {
	return s.Width > MaxSize() || s.Height > MaxSize()
}

// Limit returns the specified maximum size if this size is larger, otherwise the size itself.
func (s Size) Limit(maxSize Size) Size {
	if s.Width > maxSize.Width || s.Height > maxSize.Height {
		return maxSize
	}

	return s
}

// Clamp returns the largest renderable size if this size exceeds the limit.
// It resolves to a "fit" size, as proportional resizing preserves the whole image.
func (s Size) Clamp() Size {
	if !s.ExceedsLimit() {
		return s
	}

	for _, size := range FitSizes {
		if size.Width <= MaxSize() && size.Height <= MaxSize() {
			return size
		}
	}

	return SizeFit720
}

// FromCache returns the filename if a thumbnail image with the matching size is in the cache.
func (s Size) FromCache(fileName, fileHash, cachePath string) (string, error) {
	return FromCache(fileName, fileHash, cachePath, s.Width, s.Height, s.Options...)
}

// FromFile generates a new thumbnail with the requested size, if it does not already exist, and returns its filename.
func (s Size) FromFile(fileName, fileHash, cachePath string, fileOrientation int) (string, error) {
	return FromFile(fileName, fileHash, cachePath, s.Width, s.Height, fileOrientation, s.Options...)
}

// Create creates a thumbnail with the matching size and returns it as image.Image.
func (s Size) Create(img image.Image, fileName string) (image.Image, error) {
	return Create(img, fileName, s.Width, s.Height, s.Options...)
}

// FileName returns the file name of the thumbnail for the matching size.
func (s Size) FileName(hash, thumbPath string) (string, error) {
	return FileName(hash, thumbPath, s.Width, s.Height, s.Options...)
}

// ResolvedName returns the file name of the thumbnail for the matching size with all symlinks resolved.
func (s Size) ResolvedName(hash, thumbPath string) (string, error) {
	return ResolvedName(hash, thumbPath, s.Width, s.Height, s.Options...)
}

// Skip tests if this size can be skipped when generating thumbnails, e.g. because it is larger than the original.
func (s Size) Skip(img image.Image) bool {
	return Skip(s, img.Bounds())
}

// Skip tests if the size can be skipped when generating thumbnails, e.g. because it is larger than the original.
func Skip(s Size, bounds image.Rectangle) bool {
	// Always return false if this thumbnail size is always required.
	if s.Required {
		return false
	}

	// Optional sizes can be skipped by default.
	if s.Optional {
		return true
	}

	// Skip square thumbnails that show a crop on the left or right if the image is square as well.
	if bounds.Max.X == bounds.Max.Y && s.Width == s.Height {
		if s.Options.Contains(ResampleFillTopLeft) || s.Options.Contains(ResampleFillBottomRight) {
			return true
		}
	}

	// Check if image is within the bounds of this thumbnail size or is fitted to it.
	if !s.Fit || !bounds.In(s.Bounds()) {
		return false
	}

	// Skip if the image is smaller than this thumbnail size.
	if newSize := FitBounds(bounds); newSize.Width < s.Width {
		return true
	}

	return false
}
