// Code generated by go generate; DO NOT EDIT.
package migrate

var DialectSQLite = Migrations{
	{
		ID:      "20211121-094727",
		Dialect: "sqlite",
		Query:   "DROP INDEX IF EXISTS idx_places_place_label ON places;",
	},
}
