// Code generated by go generate; DO NOT EDIT.
package migrate

var DialectMySQL = Migrations{
	{
		ID:      "20211121-094727",
		Dialect: "mysql",
		Query:   "DROP INDEX IF EXISTS uix_places_place_label ON places;",
	},
}
