DROP DATABASE IF EXISTS migrate;
CREATE DATABASE IF NOT EXISTS migrate;
CREATE USER IF NOT EXISTS migrate@'%' IDENTIFIED BY 'migrate';
GRANT ALL PRIVILEGES ON migrate.* TO migrate@'%';

FLUSH PRIVILEGES;
