export default {
  mode: "user",
  name: "PhotoPrism",
  about: "PhotoPrism® CE",
  edition: "ce",
  version: "210710-bae1f2d7-Linux-x86_64-DEBUG",
  copyright: "(c) 2018-2025 PhotoPrism UG. All rights reserved.",
  flags: "public debug develop experimental settings",
  baseUri: "",
  staticUri: "/static",
  apiUri: "/api/v1",
  contentUri: "/api/v1",
  siteUrl: "http://localhost:2342/",
  sitePreview: "http://localhost:2342/static/img/preview.jpg",
  siteTitle: "PhotoPrism",
  siteCaption: "AI-Powered Photos App",
  siteDescription: "Open-Source Photo Management",
  siteAuthor: "@photoprism_app",
  debug: false,
  readonly: false,
  uploadNSFW: false,
  public: false,
  develop: true,
  experimental: true,
  disableSettings: false,
  test: true,
  demo: false,
  sponsor: true,
  albumCategories: ["Animal", "Holiday"],
  albums: [
    {
      ID: 69,
      UID: "aqw0vmr32zb4560f",
      Slug: "test-album-1",
      Type: "album",
      Title: "Test Album 1",
      Favorite: true,
      Private: false,
    },
    {
      ID: 70,
      UID: "aqw0vmzrkc202vty",
      Slug: "test-album-2",
      Type: "album",
      Title: "Test Album 2",
      Favorite: true,
      Private: false,
    },
  ],
  cameras: [
    {
      ID: 7,
      Slug: "apple-iphone-se",
      Name: "Apple iPhone SE",
      Make: "Apple",
      Model: "iPhone SE",
    },
    {
      ID: 2,
      Slug: "canon-eos-6d",
      Name: "Canon EOS 6D",
      Make: "Canon",
      Model: "EOS 6D",
    },
  ],
  mapKey: "D9ve6edlcVR2mEsNvCXa",
  downloadToken: "2lbh9x09",
  previewToken: "public",
  settings: {
    ui: {
      scrollbar: true,
      zoom: false,
      theme: "default",
      language: "en",
    },
    search: {
      batchSize: 90,
    },
    maps: {
      animate: 0,
      style: "streets",
    },
    features: {
      upload: true,
      download: true,
      private: true,
      review: false,
      files: true,
      videos: true,
      folders: true,
      albums: true,
      moments: true,
      places: true,
      edit: true,
      share: true,
      library: true,
      import: true,
    },
  },
};
