<template>
  <v-container id="auth-login" fluid fill-height class="auth-login wallpaper background-welcome pa-6" :style="wallpaper()">
    <v-row id="auth-layout" class="auth-layout">
      <v-col cols="12" sm="9" md="6" lg="4" xl="3">
        <v-form ref="form" class="auth-login-form" accept-charset="UTF-8" @submit.prevent="onLogin">
          <v-card id="auth-login-box" class="elevation-12 auth-login-box blur-7">
            <v-card-text class="pa-6">
              <p-auth-header></p-auth-header>
              <v-spacer></v-spacer>
              <v-row align="start">
                <template v-if="enterCode">
                  <v-col cols="12" class="pa-2 pb-4 text-body-1">
                    <translate>Enter the verification code generated by your authenticator app:</translate>
                  </v-col>
                  <v-col cols="12" class="px-2 py-1">
                    <!-- TODO: change icon -->
                    <v-text-field
                      id="one-time-code"
                      key="auth-input-code"
                      ref="code"
                      v-model="code"
                      :disabled="loading"
                      name="code"
                      type="text"
                      :label="$gettext('Verification Code')"
                      mask="nnn nnn nnn nnn"
                      inputmode="text"
                      hide-details
                      required
                      variant="solo"
                      autofocus
                      autocorrect="off"
                      autocapitalize="none"
                      autocomplete="one-time-code"
                      bg-color="grey lighten-5"
                      class="input-code text-selectable"
                      prepend-inner-icon="verified_user"
                      color="primary"
                      @keyup.enter="onLogin"
                    ></v-text-field>
                  </v-col>
                </template>
                <template v-else>
                  <v-col cols="12" class="pa-2">
                    <v-text-field
                      id="auth-username"
                      key="auth-input-username"
                      v-model="username"
                      :disabled="loading || enterCode"
                      name="username"
                      type="text"
                      :label="$gettext('Name')"
                      hide-details
                      required
                      variant="solo"
                      autocorrect="off"
                      autocapitalize="none"
                      autocomplete="username"
                      bg-color="grey lighten-5"
                      class="input-username text-selectable"
                      color="primary"
                      prepend-inner-icon="mdi-account"
                      @keyup.enter="onLogin"
                    ></v-text-field>
                  </v-col>
                  <v-col cols="12" class="px-2 py-1">
                    <v-text-field
                      id="auth-password"
                      key="auth-input-password"
                      v-model="password"
                      :disabled="loading"
                      name="password"
                      :type="showPassword ? 'text' : 'password'"
                      :label="$gettext('Password')"
                      hide-details
                      required
                      variant="solo"
                      autocorrect="off"
                      autocapitalize="none"
                      autocomplete="current-password"
                      bg-color="grey lighten-5"
                      class="input-password text-selectable"
                      :append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                      prepend-inner-icon="mdi-lock"
                      color="primary"
                      @click:append="showPassword = !showPassword"
                      @keyup.enter="onLogin"
                    ></v-text-field>
                  </v-col>
                </template>
                <v-col cols="12" class="px-2 pt-1 pb-0 auth-actions">
                  <div class="action-buttons auth-buttons text-center">
                    <v-btn v-if="enterCode" :color="colors.secondary" variant="outlined" :block="$vuetify.display.xs" :style="`color: ${colors.link}!important`" class="action-cancel ra-6 px-4 py-2 opacity-80" @click.stop.prevent="onCancel">
                      <translate>Cancel</translate>
                    </v-btn>
                    <v-btn v-else-if="registerUri" :color="colors.secondary" variant="outlined" :block="$vuetify.display.xs" :style="`color: ${colors.link}!important`" class="action-register ra-6 px-4 py-2 opacity-80" @click.stop.prevent="onRegister">
                      <translate>Create Account</translate>
                    </v-btn>
                    <v-btn :color="colors.primary" variant="flat" :disabled="loginDisabled" :block="$vuetify.display.xs" class="text-white action-confirm ra-6 py-2 px-4" @click.stop.prevent="onLogin">
                      <translate>Sign in</translate>
                      <v-icon v-if="rtl" start>mdi-chevron-left</v-icon>
                      <v-icon v-else end>mdi-chevron-right</v-icon>
                    </v-btn>
                  </div>
                  <div v-if="enterCode" class="auth-links text-center opacity-80">
                    <translate>Can't access your authenticator app or device?</translate>
                    <translate>Use your recovery code or contact an administrator for help.</translate>
                  </div>
                  <div v-else-if="passwordResetUri" class="auth-links text-center opacity-80">
                    <a :href="passwordResetUri" class="text-link link--text">
                      <translate>Forgot password?</translate>
                    </a>
                  </div>
                </v-col>
                <template v-if="config.ext.oidc.enabled && !enterCode">
                  <v-col cols="12" class="px-2 pb-4 oidc-actions">
                    <v-divider :dark="true"></v-divider>
                    <div class="text-center oidc-buttons pt-6">
                      <v-btn :color="colors.primary" variant="flat" :disabled="loading" block class="text-white action-oidc-login ra-6 my-0 py-0 px-4" @click.stop.prevent="onOidcLogin">
                        <img alt="" class="oidc-icon v-icon--left theme--dark" :src="config.ext.oidc.icon" />
                        <translate :translate-params="{ provider: config.ext.oidc.provider }">Continue with %{provider}</translate>
                      </v-btn>
                    </div>
                  </v-col>
                </template>
              </v-row>
            </v-card-text>
          </v-card>
        </v-form>
      </v-col>
    </v-row>
    <p-auth-footer :colors="colors"></p-auth-footer>
  </v-container>
</template>

<script>
export default {
  name: "PPageLogin",
  data() {
    return {
      colors: {
        accent: "#05dde1",
        primary: "#00a6a9",
        secondary: "#505050",
        link: "#c8e3e7",
      },
      loading: false,
      username: "",
      password: "",
      showPassword: false,
      code: "",
      enterCode: false,
      sponsor: this.$config.isSponsor(),
      config: this.$config.values,
      siteDescription: this.$config.getSiteDescription(),
      nextUrl: this.$route.params.nextUrl ? this.$route.params.nextUrl : "/",
      wallpaperUri: this.$config.values.wallpaperUri,
      registerUri: this.$config.values.registerUri,
      passwordResetUri: this.$config.values.passwordResetUri,
      rtl: this.$rtl,
    };
  },
  computed: {
    loginDisabled() {
      return this.loading || this.username.trim() === "" || this.password.trim() === "";
    },
  },
  created() {
    this.$scrollbar.hide(this.$isMobile);
    const authError = window.localStorage.getItem("authError");
    if (authError) {
      this.$notify.error(authError);
      window.localStorage.removeItem("authError");
    }
  },
  unmounted() {
    this.$scrollbar.show();
  },
  methods: {
    wallpaper() {
      if (this.wallpaperUri) {
        return `background-image: url(${this.wallpaperUri});`;
      }

      return "";
    },
    load() {
      this.$notify.blockUI();

      let route = this.$router.resolve({
        name: this.$session.getHome(),
      });

      setTimeout(() => {
        window.location = route.href;
      }, 100);
    },
    reset() {
      this.username = "";
      this.password = "";
      this.showPassword = false;
      this.code = "";
      this.enterCode = false;
    },
    onCancel() {
      if (this.loading) {
        return;
      }
      this.reset();
    },
    onRegister() {
      window.location = this.registerUri;
    },
    onLogin() {
      const username = this.username.trim();
      const password = this.password.trim();
      const code = this.code.trim();

      if (username === "" || password === "") {
        return;
      }

      this.loading = true;
      this.$session
        .login(username, password, code)
        .then(() => {
          this.load();
        })
        .catch((e) => {
          if (e.response?.data?.code === 32) {
            this.enterCode = true;
            this.$nextTick(() => this.$refs.code.focus());
          }
          this.loading = false;
        });
    },
    onOidcLogin() {
      if (this.loading) {
        return;
      }

      if (this.config.ext?.oidc?.loginUri) {
        this.loading = true;
        this.$nextTick(() => {
          window.location = this.config.ext.oidc.loginUri;
        });
      } else {
        this.$notify.warn(this.$gettext("Missing or invalid configuration"));
      }
    },
  },
};
</script>
