<template>
  <v-container id="auth-login" theme="login" fluid fill-height class="auth-login wallpaper background-welcome pa-6" :style="wallpaper()">
    <v-theme-provider theme="login">
      <v-row id="auth-layout" class="auth-layout">
        <v-col cols="12" sm="9" md="6" lg="4" xl="3">
          <v-form ref="form" class="auth-login-form" accept-charset="UTF-8" @submit.prevent="onLogin">
            <v-card id="auth-login-box" class="elevation-12 auth-login-box blur-7">
              <v-card-text class="pa-6">
                <p-auth-header></p-auth-header>
                <v-spacer></v-spacer>
                <v-row align="start">
                  <template v-if="enterCode">
                    <v-col cols="12" class="pa-2 pb-4 text-body-1">
                      <translate>Enter the verification code generated by your authenticator app:</translate>
                    </v-col>
                    <v-col cols="12" class="px-2 py-1">
                      <!-- TODO: change icon -->
                      <v-text-field
                        id="one-time-code"
                        key="auth-input-code"
                        ref="code"
                        v-model="code"
                        :disabled="loading"
                        name="code"
                        variant="solo"
                        type="text"
                        :placeholder="$gettext('Verification Code')"
                        mask="nnn nnn nnn nnn"
                        inputmode="text"
                        hide-details
                        required
                        autofocus
                        autocorrect="off"
                        autocapitalize="none"
                        autocomplete="one-time-code"
                        class="input-code text-selectable"
                        prepend-inner-icon="verified_user"
                        @keyup.enter="onLogin"
                      ></v-text-field>
                    </v-col>
                  </template>
                  <template v-else>
                    <v-col cols="12" class="pa-2">
                      <v-text-field
                        id="auth-username"
                        key="auth-input-username"
                        v-model="username"
                        :disabled="loading || enterCode"
                        name="username"
                        variant="solo"
                        density="comfortable"
                        type="text"
                        :placeholder="$gettext('Name')"
                        hide-details
                        required
                        autocorrect="off"
                        autocapitalize="none"
                        autocomplete="username"
                        class="input-username text-selectable"
                        prepend-inner-icon="mdi-account"
                        @keyup.enter="onLogin"
                      ></v-text-field>
                    </v-col>
                    <v-col cols="12" class="px-2 py-1">
                      <v-text-field
                        id="auth-password"
                        key="auth-input-password"
                        v-model="password"
                        :disabled="loading"
                        name="password"
                        variant="solo"
                        density="comfortable"
                        :type="showPassword ? 'text' : 'password'"
                        :placeholder="$gettext('Password')"
                        hide-details
                        required
                        autocorrect="off"
                        autocapitalize="none"
                        autocomplete="current-password"
                        class="input-password text-selectable"
                        :append-inner-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                        prepend-inner-icon="mdi-lock"
                        @click:append-inner="showPassword = !showPassword"
                        @keyup.enter="onLogin"
                      ></v-text-field>
                    </v-col>
                  </template>
                  <v-col cols="12" class="px-2 pt-1 pb-0 auth-actions">
                    <div class="action-buttons auth-buttons d-flex ga-3 align-center justify-center">
                      <v-btn v-if="enterCode" color="primary-button" variant="outlined" :block="$vuetify.display.xs" class="action-cancel opacity-80" @click.stop.prevent="onCancel">
                        <translate>Cancel</translate>
                      </v-btn>
                      <v-btn v-else-if="registerUri" color="primary-button" variant="outlined" :block="$vuetify.display.xs" class="action-register opacity-80" @click.stop.prevent="onRegister">
                        <translate>Create Account</translate>
                      </v-btn>
                      <v-btn color="primary-button" variant="flat" :disabled="loginDisabled" :block="$vuetify.display.xs" class="action-confirm" @click.stop.prevent="onLogin">
                        <translate>Sign in</translate>
                        <v-icon v-if="rtl" start>mdi-chevron-left</v-icon>
                        <v-icon v-else end>mdi-chevron-right</v-icon>
                      </v-btn>
                    </div>
                    <div v-if="enterCode" class="auth-links text-center opacity-80">
                      <translate>Can't access your authenticator app or device?</translate>
                      <translate>Use your recovery code or contact an administrator for help.</translate>
                    </div>
                    <div v-else-if="passwordResetUri" class="auth-links text-center opacity-80">
                      <a :href="passwordResetUri" class="text-link link--text">
                        <translate>Forgot password?</translate>
                      </a>
                    </div>
                  </v-col>
                  <template v-if="config.ext.oidc.enabled && !enterCode">
                    <v-col cols="12" class="px-2 pb-4 oidc-actions">
                      <v-divider />
                      <div class="text-center oidc-buttons pt-6">
                        <v-btn color="primary-button" variant="flat" :disabled="loading" block class="action-oidc-login" @click.stop.prevent="onOidcLogin">
                          <img alt="" class="oidc-icon v-icon--left mx-1" :src="config.ext.oidc.icon" />
                          <translate :translate-params="{ provider: config.ext.oidc.provider }">Continue with %{provider}</translate>
                        </v-btn>
                      </div>
                    </v-col>
                  </template>
                </v-row>
              </v-card-text>
            </v-card>
          </v-form>
        </v-col>
      </v-row>
      <p-auth-footer :colors="colors"></p-auth-footer>
    </v-theme-provider>
  </v-container>
</template>

<script>
export default {
  name: "PPageLogin",
  data() {
    return {
      colors: {
        accent: "#05dde1",
        primary: "#00a6a9",
        secondary: "#505050",
        link: "#c8e3e7",
      },
      loading: false,
      username: "",
      password: "",
      showPassword: false,
      code: "",
      enterCode: false,
      sponsor: this.$config.isSponsor(),
      config: this.$config.values,
      siteDescription: this.$config.getSiteDescription(),
      nextUrl: this.$route.params.nextUrl ? this.$route.params.nextUrl : "/",
      wallpaperUri: this.$config.values.wallpaperUri,
      registerUri: this.$config.values.registerUri,
      passwordResetUri: this.$config.values.passwordResetUri,
      rtl: this.$rtl,
    };
  },
  computed: {
    loginDisabled() {
      return this.loading || this.username.trim() === "" || this.password.trim() === "";
    },
  },
  created() {
    this.$scrollbar.hide(this.$isMobile);
    const authError = window.localStorage.getItem("authError");
    if (authError) {
      this.$notify.error(authError);
      window.localStorage.removeItem("authError");
    }
  },
  unmounted() {
    this.$scrollbar.show();
  },
  methods: {
    wallpaper() {
      if (this.wallpaperUri) {
        return `background-image: url(${this.wallpaperUri});`;
      }

      return "";
    },
    load() {
      this.$notify.blockUI();

      let route = this.$router.resolve({
        name: this.$session.getHome(),
      });

      setTimeout(() => {
        window.location = route.href;
      }, 100);
    },
    reset() {
      this.username = "";
      this.password = "";
      this.showPassword = false;
      this.code = "";
      this.enterCode = false;
    },
    onCancel() {
      if (this.loading) {
        return;
      }
      this.reset();
    },
    onRegister() {
      window.location = this.registerUri;
    },
    onLogin() {
      const username = this.username.trim();
      const password = this.password.trim();
      const code = this.code.trim();

      if (username === "" || password === "") {
        return;
      }

      this.loading = true;
      this.$session
        .login(username, password, code)
        .then(() => {
          this.load();
        })
        .catch((e) => {
          if (e.response?.data?.code === 32) {
            this.enterCode = true;
            this.$nextTick(() => this.$refs.code.focus());
          }
          this.loading = false;
        });
    },
    onOidcLogin() {
      if (this.loading) {
        return;
      }

      if (this.config.ext?.oidc?.loginUri) {
        this.loading = true;
        this.$nextTick(() => {
          window.location = this.config.ext.oidc.loginUri;
        });
      } else {
        this.$notify.warn(this.$gettext("Missing or invalid configuration"));
      }
    },
  },
};
</script>
