package acl

// ResourceNames contains a list of all specified resources.
var ResourceNames = []Resource{
	ResourceFiles,
	ResourceFolders,
	ResourceShares,
	ResourcePhotos,
	ResourceVideos,
	ResourceFavorites,
	ResourceAlbums,
	ResourceMoments,
	ResourceCalendar,
	ResourcePeople,
	ResourcePlaces,
	ResourceLabels,
	ResourceConfig,
	ResourceSettings,
	ResourcePasscode,
	ResourcePassword,
	ResourceServices,
	ResourceUsers,
	ResourceSessions,
	ResourceLogs,
	ResourceApi,
	ResourceWebDAV,
	ResourceWebhooks,
	ResourceMetrics,
	ResourceVision,
	ResourceFeedback,
	ResourceDefault,
}
