package acl

// ScopeDescriptions maps supported authorization scopes to human-readable summaries for CLI help and docs.
var ScopeDescriptions = map[string]string{
	"*":                        "Wildcard granting full access to every resource and permission.",
	ScopeRead.String():         "Read-only access across all resources (search, view, download).",
	ScopeWrite.String():        "Write access across all resources (create, update, delete) without implicit read permissions.",
	ResourceFiles.String():     "Full access to original and derived files on disk.",
	ResourceFolders.String():   "Manage virtual folders derived from the filesystem.",
	ResourceShares.String():    "Manage share links and published collections.",
	ResourcePhotos.String():    "Operate on photo library items and metadata.",
	ResourceVideos.String():    "Operate on video library items and metadata.",
	ResourceFavorites.String(): "Manage the favorites collection.",
	ResourceAlbums.String():    "Create and manage albums.",
	ResourceMoments.String():   "Access automatically grouped moments and events.",
	ResourceCalendar.String():  "Access calendar-based timelines.",
	ResourcePeople.String():    "Manage people records and face assignments.",
	ResourcePlaces.String():    "Access maps, locations, and place clusters.",
	ResourceLabels.String():    "Manage subject labels and keywords.",
	ResourceConfig.String():    "Read configuration reports and summaries.",
	ResourceSettings.String():  "Read and update application settings.",
	ResourcePasscode.String():  "Manage app passcodes and guest access codes.",
	ResourcePassword.String():  "Manage user password change and reset endpoints.",
	ResourceServices.String():  "Manage connected services and integrations.",
	ResourceUsers.String():     "Administer user accounts and profiles.",
	ResourceSessions.String():  "Inspect and revoke active sessions and tokens.",
	ResourceLogs.String():      "Read system, audit, and application logs.",
	ResourceApi.String():       "Call generic API endpoints outside other scopes.",
	ResourceWebDAV.String():    "Access the WebDAV interface for syncing files.",
	ResourceWebhooks.String():  "Manage webhook subscriptions and deliveries.",
	ResourceMetrics.String():   "Read operational metrics for monitoring.",
	ResourceVision.String():    "Use AI vision endpoints and related queues.",
	ResourceCluster.String():   "Manage cluster registration and node state.",
	ResourceFeedback.String():  "Submit and review feedback or support reports.",
	ResourceDefault.String():   "Fallback for endpoints without a dedicated resource tag.",
}
