package txt

// Generated code, do not edit.

var Countries = map[string]string{
	"andorra":            "ad",
	"france":             "fr",
	"frankreich":         "fr",
	"bratislava":         "sk",
	"slovakia":           "sk",
	"austria":            "at",
	"hallstatt":          "at",
	"wörthersee":         "at",
	"österreich":         "at",
	"vienna":             "at",
	"wien":               "at",
	"salzburg":           "at",
	"sölden":             "at",
	"klagenfurt":         "at",
	"innsbruck":          "at",
	"hungary":            "hu",
	"georgia republic":   "ge",
	"vatican city":       "va",
	"poland":             "pl",
	"warsaw":             "pl",
	"warschau":           "pl",
	"cambodia":           "kh",
	"vientiane":          "la",
	"lao republic":       "la",
	"laos":               "la",
	"vietnam":            "vn",
	"denmark":            "dk",
	"myanmar":            "mm",
	"czechia":            "cz",
	"czech":              "cz",
	"karlovy vary":       "cz",
	"zurich":             "ch",
	"zürich":             "ch",
	"st gallen":          "ch",
	"basel":              "ch",
	"interlaken":         "ch",
	"lauterbrunnen":      "ch",
	"grindelwald":        "ch",
	"lucerne":            "ch",
	"luzern":             "ch",
	"switzerland":        "ch",
	"swiss":              "ch",
	"schweiz":            "ch",
	"belgium":            "be",
	"sweden":             "se",
	"sverige":            "se",
	"schweden":           "se",
	"gotland":            "se",
	"öland":              "se",
	"faroe":              "fo",
	"albania":            "al",
	"macedonia":          "mk",
	"montenegro":         "me",
	"finland":            "fi",
	"san marino":         "sm",
	"moldova":            "md",
	"belarus":            "by",
	"brazil":             "br",
	"brasil":             "br",
	"russia":             "ru",
	"ukraine":            "ua",
	"united kingdom":     "gb",
	"london":             "gb",
	"scotland":           "gb",
	"edinburgh":          "gb",
	"england":            "gb",
	"britain":            "gb",
	"buckingham":         "gb",
	"isle of man":        "im",
	"ireland":            "ie",
	"dublin":             "ie",
	"deutschland":        "de",
	"germany":            "de",
	"aachen":             "de",
	"steglitz":           "de",
	"kreuzberg":          "de",
	"kreuzberger":        "de",
	"neukölln":           "de",
	"neuköllner":         "de",
	"friedrichshain":     "de",
	"berghain":           "de",
	"bundestag":          "de",
	"bundesrat":          "de",
	"potsdam":            "de",
	"potsdamer":          "de",
	"brandenburg":        "de",
	"brandenburger":      "de",
	"grunewald":          "de",
	"charlottenburg":     "de",
	"wilmersdorf":        "de",
	"tempelhof":          "de",
	"tempelhofer":        "de",
	"schönefeld":         "de",
	"schönefelder":       "de",
	"reichstag":          "de",
	"kassel":             "de",
	"ostsee":             "de",
	"nordsee":            "de",
	"wannsee":            "de",
	"berlin":             "de",
	"pfalz":              "de",
	"mannheim":           "de",
	"heidelberg":         "de",
	"heidelberger":       "de",
	"stuttgart":          "de",
	"stuttgarter":        "de",
	"bisingen":           "de",
	"balingen":           "de",
	"hechingen":          "de",
	"swabian":            "de",
	"schwarzwald":        "de",
	"schwarzwälder":      "de",
	"schwaben":           "de",
	"schwäbisch":         "de",
	"schwäbische":        "de",
	"schwäbisches":       "de",
	"albtrauf":           "de",
	"münchen":            "de",
	"münchner":           "de",
	"oktoberfest":        "de",
	"württemberg":        "de",
	"bayern":             "de",
	"bavaria":            "de",
	"bairisch":           "de",
	"bavarian":           "de",
	"erfurt":             "de",
	"leipzig":            "de",
	"leipziger":          "de",
	"schwerin":           "de",
	"greifswald":         "de",
	"greifswalder":       "de",
	"dresden":            "de",
	"dresdener":          "de",
	"nebelhorn":          "de",
	"neuschwanstein":     "de",
	"nürnberg":           "de",
	"würzburg":           "de",
	"munich":             "de",
	"frankfurt":          "de",
	"freiburg":           "de",
	"freiburger":         "de",
	"hamburg":            "de",
	"tübingen":           "de",
	"tubingen":           "de",
	"tübinger":           "de",
	"köln":               "de",
	"kölner":             "de",
	"königsee":           "de",
	"dortmund":           "de",
	"düsseldorf":         "de",
	"cologne":            "de",
	"saarland":           "de",
	"saarbrücken":        "de",
	"konstanz":           "de",
	"konstanzer":         "de",
	"reichenau":          "de",
	"meckenheim":         "de",
	"wiesbaden":          "de",
	"lahnstein":          "de",
	"augsburg":           "de",
	"augsburger":         "de",
	"freinsheim":         "de",
	"speyer":             "de",
	"marburg":            "de",
	"marburger":          "de",
	"mechtersheim":       "de",
	"dürkheim":           "de",
	"ulm":                "de",
	"neckarsulm":         "de",
	"zugspitze":          "de",
	"sächsische schweiz": "de",
	"latvia":             "lv",
	"lettland":           "lv",
	"lithuania":          "lt",
	"litauen":            "lt",
	"estonia":            "ee",
	"australia":          "au",
	"melbourne":          "au",
	"perth":              "au",
	"tasmania":           "au",
	"tasmanien":          "au",
	"sydney":             "au",
	"capetown":           "za",
	"durban":             "za",
	"pretoria":           "za",
	"kapstadt":           "za",
	"johannesburg":       "za",
	"south africa":       "za",
	"eswatini":           "sz",
	"swaziland":          "sz",
	"romania":            "ro",
	"ecuador":            "ec",
	"mexico":             "mx",
	"colombia":           "co",
	"california":         "us",
	"washington":         "us",
	"new york":           "us",
	"nyc":                "us",
	"florida":            "us",
	"cape canaveral":     "us",
	"san francisco":      "us",
	"oakland":            "us",
	"san diego":          "us",
	"los angeles":        "us",
	"seattle":            "us",
	"chicago":            "us",
	"miami":              "us",
	"dallas":             "us",
	"houston":            "us",
	"las vegas":          "us",
	"minneapolis":        "us",
	"kansas":             "us",
	"wisconsin":          "us",
	"michigan":           "us",
	"illinois":           "us",
	"boston":             "us",
	"massachusetts":      "us",
	"connecticut":        "us",
	"new jersey":         "us",
	"delaware":           "us",
	"orlando":            "us",
	"detroit":            "us",
	"nevada":             "us",
	"texas":              "us",
	"usa":                "us",
	"united states":      "us",
	"venice beach":       "us",
	"mongolia":           "mn",
	"chile":              "cl",
	"rwanda":             "rw",
	"turkey":             "tr",
	"türkei":             "tr",
	"istanbul":           "tr",
	"ankara":             "tr",
	"izmir":              "tr",
	"bursa":              "tr",
	"antalya":            "tr",
	"konya":              "tr",
	"adana":              "tr",
	"gaziantep":          "tr",
	"kocaeli":            "tr",
	"mersin":             "tr",
	"diyarbakır":         "tr",
	"kyrgyzstan":         "kg",
	"bhutan":             "bt",
	"everest":            "np",
	"nepal":              "np",
	"himalaya":           "np",
	"kathmandu":          "np",
	"bangladesh":         "bd",
	"dhaka":              "bd",
	"chattogram":         "bd",
	"khulna":             "bd",
	"jordan":             "jo",
	"amman":              "jo",
	"عَمَّان":            "jo",
	"zarqa":              "jo",
	"الزرقاء":            "jo",
	"irbid":              "jo",
	"إربد":               "jo",
	"russeifa":           "jo",
	"الرصيفة":            "jo",
	"sahab":              "jo",
	"سحاب":               "jo",
	"ar ramtha":          "jo",
	"الرمثا":             "jo",
	"aqaba":              "jo",
	"العقبة":             "jo",
	"mafraq":             "jo",
	"المفرق":             "jo",
	"syria":              "sy",
	"سوريا":              "sy",
	"syrien":             "sy",
	"damascus":           "sy",
	"دِمَشق":             "sy",
	"aleppo":             "sy",
	"ﺣَﻠَﺐ":              "sy",
	"ḥalab":              "sy",
	"daraa":              "sy",
	"دَرْعَا":            "sy",
	"ad-deir":            "sy",
	"deir ez-zor":        "sy",
	"دير الزور":          "sy",
	"al-hasakah":         "sy",
	"لْحَسَكَة":          "sy",
	"latakia":            "sy",
	"للَّاذْقِيَّة":      "sy",
	"quneitra":           "sy",
	"al qunaytirah":      "sy",
	"qunaitira":          "sy",
	"kuneitra":           "sy",
	"لْقُنَيطْرَة":       "sy",
	"idlib":              "sy",
	"in homs":            "sy",
	"qusseir":            "sy",
	"raqqa":              "sy",
	"ar-raqqah":          "sy",
	"rakka":              "sy",
	"ٱلرَّقَّة":          "sy",
	"afrin":              "sy",
	"ifrin":              "sy",
	"efrin":              "sy",
	"عفرين":              "sy",
	"lebanon":            "lb",
	"لُبْنان":            "lb",
	"beirut":             "lb",
	"بيروت":              "lb",
	"dahieh":             "lb",
	"dahiyeh":            "lb",
	"dâhiye":             "lb",
	"al-dahyeh":          "lb",
	"nabatieh":           "lb",
	"byblos":             "lb",
	"baalbek":            "lb",
	"baalbeck":           "lb",
	"بعلبك":              "lb",
	"quobeiyat":          "lb",
	"rafic hariri":       "lb",
	"kafarkila":          "lb",
	"kfarkila":           "lb",
	"kfarkela":           "lb",
	"kafarkela":          "lb",
	"kafr kila":          "lb",
	"كفركلا":             "lb",
	"mhaibib":            "lb",
	"ghobeiri":           "lb",
	"ghobeiry":           "lb",
	"غبيري":              "lb",
	"in sidon":           "lb",
	"صيدا":               "lb",
	"in tyre":            "lb",
	"صُور":               "lb",
	"bulgaria":           "bg",
	"koprivshtitsa":      "bg",
	"melnik":             "bg",
	"sofia":              "bg",
	"corfu":              "gr",
	"greece":             "gr",
	"hellas":             "gr",
	"north korea":        "kp",
	"dprk":               "kp",
	"dpr korea":          "kp",
	"algeria":            "dz",
	"tunisia":            "tn",
	"libya":              "ly",
	"mauritania":         "mr",
	"gambia":             "gm",
	"senegal":            "sn",
	"guinea bissau":      "gw",
	"sierra leone":       "sl",
	"guinea":             "gn",
	"ivory coast":        "ci",
	"liberia":            "lr",
	"ghana":              "gh",
	"togo":               "tg",
	"burkina faso":       "bf",
	"benin":              "bj",
	"mali":               "ml",
	"niger":              "ne",
	"nigeria":            "ng",
	"sudan":              "sd",
	"central african":    "cf",
	"equatorial guinea":  "gq",
	"gabon":              "ga",
	"congo brazzaville":  "cg",
	"congo":              "cd",
	"uganda":             "ug",
	"kenya":              "ke",
	"somalia":            "so",
	"ethiopia":           "et",
	"djibouti":           "dj",
	"cameroon":           "cm",
	"namibia":            "na",
	"angola":             "ao",
	"burundi":            "bi",
	"tanzania":           "tz",
	"zambia":             "zm",
	"zimbabwe":           "zw",
	"rhodesia":           "zw",
	"mozambique":         "mz",
	"malawi":             "mw",
	"uzbekistan":         "uz",
	"tajikistan":         "tj",
	"kazakhstan":         "kz",
	"croatia":            "hr",
	"slovenia":           "si",
	"ljubljana":          "si",
	"turkmenistan":       "tm",
	"ashgabat":           "tm",
	"bolivia":            "bo",
	"guernsey":           "gg",
	"china":              "cn",
	"shanghai":           "cn",
	"上海市":                "cn",
	"peking":             "cn",
	"北京市":                "cn",
	"beijing":            "cn",
	"venezuela":          "ve",
	"caracas":            "ve",
	"virgin island":      "vg",
	"charlotte amalie":   "vg",
	"argentina":          "ar",
	"argentine":          "ar",
	"buenos aires":       "ar",
	"uruguay":            "uy",
	"montevideo":         "uy",
	"paraguay":           "py",
	"asunción":           "py",
	"suriname":           "sr",
	"guyana":             "gy",
	"nicaragua":          "ni",
	"managua":            "ni",
	"costa rica":         "cr",
	"panama":             "pa",
	"honduras":           "hn",
	"tegucigalpa":        "hn",
	"belize":             "bz",
	"peru":               "pe",
	"lima":               "pe",
	"portugal":           "pt",
	"lisboa":             "pt",
	"lisbon":             "pt",
	"lissabon":           "pt",
	"eritrea":            "er",
	"iceland":            "is",
	"ísland":             "is",
	"reykjavík":          "is",
	"reykjavik":          "is",
	"keflavík":           "is",
	"vatnajökull":        "is",
	"afghanistan":        "af",
	"india":              "in",
	"indien":             "in",
	"bhārat gaṇarājya":   "in",
	"mumbai":             "in",
	"muṁbaī":             "in",
	"bombay":             "in",
	"maharashtra":        "in",
	"new delhi":          "in",
	"naī dillī":          "in",
	"bangalore":          "in",
	"hyderabad":          "in",
	"ahmedabad":          "in",
	"chennai":            "in",
	"kolkata":            "in",
	"jaipur":             "in",
	"lucknow":            "in",
	"indonesia":          "id",
	"jakarta":            "id",
	"surabaya":           "id",
	"bandung":            "id",
	"balikpapan":         "id",
	"denpasar":           "id",
	"bali":               "id",
	"iraq":               "iq",
	"irak":               "iq",
	"baghdad":            "iq",
	"العراق":             "iq",
	"بَغْدَاد":           "iq",
	"mosul":              "iq",
	"nineveh":            "iq",
	"basra":              "iq",
	"kirkuk":             "iq",
	"erbil":              "iq",
	"hewlêr":             "iq",
	"أربيل":              "iq",
	"ܐܲܪܒܹܝܠ":            "iq",
	"هەولێر":             "iq",
	"najaf":              "iq",
	"karbala":            "iq",
	"sulaymaniyah":       "iq",
	"nasiriyah":          "iq",
	"dhi qar":            "iq",
	"iran":               "ir",
	"إيران":              "ir",
	"tehran":             "ir",
	"tehrān":             "ir",
	"teheran":            "ir",
	"تهران":              "ir",
	"طهران":              "ir",
	"طَهْران":            "ir",
	"shamsabad":          "ir",
	"shams abad":         "ir",
	"شمس اباد":           "ir",
	"shamsābād":          "ir",
	"parchin":            "ir",
	"پارچین":             "ir",
	"shahroud":           "ir",
	"schahrud":           "ir",
	"شاهرود":             "ir",
	"isfahan":            "ir",
	"اصفهان":             "ir",
	"bushehr":            "ir",
	"būšehr":             "ir",
	"bushire":            "ir",
	"busheer":            "ir",
	"bouchir":            "ir",
	"mashhad":            "ir",
	"persia":             "ir",
	"yemen":              "ye",
	"اليمن":              "ye",
	"sana'a":             "ye",
	"sanaa":              "ye",
	"سناء":               "ye",
	"al hudaydah":        "ye",
	"hodeda":             "ye",
	"hodeida":            "ye",
	"hudaida":            "ye",
	"hodeidah":           "ye",
	"الْحُدَيْدَة":       "ye",
	"الحديدة":            "ye",
	"qatar":              "qa",
	"قَطَر":              "qa",
	"الدوحة":             "qa",
	"kuwait":             "kw",
	"oman":               "om",
	"east timor":         "tl",
	"pakistan":           "pk",
	"islamabad":          "pk",
	"saudi arabia":       "sa",
	"riad":               "sa",
	"riyadh":             "sa",
	"الرياض":             "sa",
	"south korea":        "kr",
	"seoul":              "kr",
	"united arab":        "ae",
	"uae":                "ae",
	"الإمارات العربية المتحدة": "ae",
	"dubai":              "ae",
	"دبي":                "ae",
	"abu dhabi":          "ae",
	"أبو ظبي":            "ae",
	"al ain":             "ae",
	"العين":              "ae",
	"sharjah":            "ae",
	"الشارقة":            "ae",
	"khor fakkan":        "ae",
	"خَوْر فَكَّان":      "ae",
	"كَلْبَاء":           "ae",
	"ajman":              "ae",
	"ras al khaimah":     "ae",
	"fujairah":           "ae",
	"umm al quwain":      "ae",
	"madinat zayed":      "ae",
	"dibba al-fujairah":  "ae",
	"cyprus":             "cy",
	"nicosia":            "cy",
	"dominica":           "dm",
	"haiti":              "ht",
	"hayti":              "ht",
	"port-au-prince":     "ht",
	"cuba":               "cu",
	"habana":             "cu",
	"guantánamo":         "cu",
	"guantanamo":         "cu",
	"varadero":           "cu",
	"hicacos":            "cu",
	"matanzas":           "cu",
	"gustavo rizo":       "cu",
	"josé martí":         "cu",
	"jose marti":         "cu",
	"new guinea":         "pg",
	"armenia":            "am",
	"yerevan":            "am",
	"azerbaijan":         "az",
	"malta":              "mt",
	"valletta":           "mt",
	"como":               "it",
	"cortina d'ampezzo":  "it",
	"italy":              "it",
	"milan":              "it",
	"milano":             "it",
	"mailand":            "it",
	"neapel":             "it",
	"palermo":            "it",
	"genua":              "it",
	"florenz":            "it",
	"bologna":            "it",
	"venezia":            "it",
	"venedig":            "it",
	"venice":             "it",
	"italien":            "it",
	"sicily":             "it",
	"trieste":            "it",
	"jersey island":      "je",
	"bahrain":            "bh",
	"japan":              "jp",
	"tokyo":              "jp",
	"東京都":                "jp",
	"fukushima":          "jp",
	"nippon":             "jp",
	"nihon":              "jp",
	"pilipinas":          "ph",
	"filipinas":          "ph",
	"philippines":        "ph",
	"madagascar":         "mg",
	"taiwan":             "tw",
	"taipei":             "tw",
	"cape verde":         "cv",
	"comoros":            "km",
	"mauritius":          "mu",
	"são tomé":           "st",
	"príncipe":           "st",
	"seychelles":         "sc",
	"seychellen":         "sc",
	"maldives":           "mv",
	"singapore":          "sg",
	"sri lanka":          "lk",
	"saint kitts":        "kn",
	"nevis":              "kn",
	"antigua":            "ag",
	"barbuda":            "ag",
	"montserrat":         "ms",
	"bahamas":            "bs",
	"turks island":       "tc",
	"caicos island":      "tc",
	"barbados":           "bb",
	"saint vincent":      "vc",
	"grenada":            "gd",
	"saint lucia":        "lc",
	"jamaica":            "jm",
	"trinidad":           "tt",
	"tobago":             "tt",
	"new zealand":        "nz",
	"kiribati":           "ki",
	"fiji":               "fj",
	"bligh island":       "fj",
	"marshall island":    "mh",
	"micronesia":         "fm",
	"nauru":              "nr",
	"palau":              "pw",
	"monaco":             "mc",
	"liechtenstein":      "li",
	"gibraltar":          "gi",
	"spain":              "es",
	"spanien":            "es",
	"andalusien":         "es",
	"andalusia":          "es",
	"canarias":           "es",
	"granada":            "es",
	"madrid":             "es",
	"barcelona":          "es",
	"córdoba":            "es",
	"seville":            "es",
	"málaga":             "es",
	"bilbao":             "es",
	"valencia":           "es",
	"españa":             "es",
	"espana":             "es",
	"canada":             "ca",
	"kanada":             "ca",
	"vancouver":          "ca",
	"british columbia":   "ca",
	"montreal":           "ca",
	"toronto":            "ca",
	"ottawa":             "ca",
	"quebec":             "ca",
	"ontario":            "ca",
	"alberta":            "ca",
	"israel":             "il",
	"israeli":            "il",
	"israelis":           "il",
	"יִשְׂרָאֵל":         "il",
	"yisra'el":           "il",
	"yisrael":            "il",
	"tel aviv":           "il",
	"תֵּל אָבִיב-יָפוֹ":  "il",
	"ben gurion":         "il",
	"caesarea":           "il",
	"netanya":            "il",
	"קֵיסָרְיָה":         "il",
	"haifa":              "il",
	"חֵיפָה":             "il",
	"bethlehem":          "il",
	"بيت لحم":            "il",
	"nazareth":           "il",
	"النَّاصِرَة":        "il",
	"jerusalem":          "il",
	"יְרוּשָׁלַיִם":      "il",
	"القُدس":             "il",
	"al-quds":            "il",
	"nhariyya":           "il",
	"ashdod":             "il",
	"אַשְׁדּוֹד":         "il",
	"ashkelon":           "il",
	"אשקלון":             "il",
	"beersheba":          "il",
	"באר שבע":            "il",
	"rishon lezion":      "il",
	"tiberias":           "il",
	"sderot":             "il",
	"mefalsim":           "il",
	"mitspe ramon":       "il",
	"kibbutz":            "il",
	"קִבּוּץ":            "il",
	"קיבוץ":              "il",
	"kibbutzim":          "il",
	"קִבּוּצִים":         "il",
	"קיבוצים":            "il",
	"degania":            "il",
	"nahal oz":           "il",
	"kfar aza":           "il",
	"kfar maimon":        "il",
	"kfar hoshen":        "il",
	"kfar masaryk":       "il",
	"in kfar":            "il",
	"be'eri":             "il",
	"egypt":              "eg",
	"ägypten":            "eg",
	"aegypten":           "eg",
	"el salvador":        "sv",
	"guatemala":          "gt",
	"niue":               "nu",
	"south sudan":        "ss",
	"serbia":             "rs",
	"solomon island":     "sb",
	"samoa":              "ws",
	"gaborone":           "bw",
	"botswana":           "bw",
	"botsuana":           "bw",
	"saint helena":       "sh",
	"sandwich island":    "gs",
	"bermuda":            "bm",
	"british indian":     "io",
	"thailand":           "th",
	"kosovo":             "xk",
	"lesotho":            "ls",
	"brunei":             "bn",
	"malaysia":           "my",
	"luxembourg":         "lu",
	"anguilla":           "ai",
	"vanuatu":            "vu",
	"tuvalu":             "tv",
	"greenland":          "gl",
	"cook island":        "ck",
	"cayman island":      "ky",
	"falkland island":    "fk",
	"pitcairn island":    "pn",
	"tokelau":            "tk",
	"tonga":              "to",
	"chamonix":           "fr",
	"réunion":            "fr",
	"strassburg":         "fr",
	"strasbourg":         "fr",
	"straßburg":          "fr",
	"paris":              "fr",
	"amsterdam":          "nl",
	"rotterdam":          "nl",
	"den haag":           "nl",
	"the hague":          "nl",
	"utrecht":            "nl",
	"eindhoven":          "nl",
	"groningen":          "nl",
	"beekse bergen":      "nl",
	"netherlands":        "nl",
	"nederland":          "nl",
	"nederlands":         "nl",
	"nederlanden":        "nl",
	"holland":            "nl",
	"chad":               "td",
	"bosnia":             "ba",
	"herzegovina":        "ba",
	"norway":             "no",
	"norwegen":           "no",
	"morocco":            "ma",
	"state of palestine": "ps",
	"فلسطين":             "ps",
	"gaza city":          "ps",
	"gaza strip":         "ps",
	"in gaza":            "ps",
	"gazans":             "ps",
	"palestinians":       "ps",
	"tulkarm":            "ps",
	"tulkarem":           "ps",
	"طولكرم":             "ps",
	"dschenin":           "ps",
	"djenin":             "ps",
	"جنين":               "ps",
	"al-aqsa":            "ps",
	"المسجد":             "ps",
	"west bank":          "ps",
	"samaria":            "ps",
	"judea":              "ps",
	"nablus":             "ps",
	"rafah":              "ps",
	"khan yunis":         "ps",
	"al mawasi":          "ps",
	"nurseirat":          "ps",
	"jabalia":            "ps",
	"beit lahia":         "ps",
	"beit hanoun":        "ps",
	"tal as sultan":      "ps",
	"tel al-sultan":      "ps",
	"ramallah":           "ps",
	"hebron":             "ps",
	"mcdonald island":    "hm",
	"heard island":       "hm",
	"europe":             "eu",
	"europa":             "eu",
	"european union":     "eu",
	"europäische union":  "eu",
	"union européenne":   "eu",
}
