package txt

// Generated code, do not edit.

var Countries = map[string]string{
	"andorra":            "ad",
	"france":             "fr",
	"frankreich":         "fr",
	"bratislava":         "sk",
	"slovakia":           "sk",
	"austria":            "at",
	"hallstatt":          "at",
	"wörthersee":         "at",
	"österreich":         "at",
	"vienna":             "at",
	"wien":               "at",
	"salzburg":           "at",
	"sölden":             "at",
	"klagenfurt":         "at",
	"innsbruck":          "at",
	"hungary":            "hu",
	"georgia republic":   "ge",
	"vatican city":       "va",
	"poland":             "pl",
	"warsaw":             "pl",
	"warschau":           "pl",
	"cambodia":           "kh",
	"vientiane":          "la",
	"lao republic":       "la",
	"laos":               "la",
	"vietnam":            "vn",
	"denmark":            "dk",
	"myanmar":            "mm",
	"czechia":            "cz",
	"czech":              "cz",
	"karlovy vary":       "cz",
	"zurich":             "ch",
	"zürich":             "ch",
	"st gallen":          "ch",
	"basel":              "ch",
	"interlaken":         "ch",
	"lauterbrunnen":      "ch",
	"grindelwald":        "ch",
	"lucerne":            "ch",
	"luzern":             "ch",
	"switzerland":        "ch",
	"swiss":              "ch",
	"schweiz":            "ch",
	"belgium":            "be",
	"sweden":             "se",
	"sverige":            "se",
	"schweden":           "se",
	"gotland":            "se",
	"öland":              "se",
	"faroe":              "fo",
	"albania":            "al",
	"macedonia":          "mk",
	"montenegro":         "me",
	"finland":            "fi",
	"san marino":         "sm",
	"moldova":            "md",
	"belarus":            "by",
	"brazil":             "br",
	"brasil":             "br",
	"russia":             "ru",
	"ukraine":            "ua",
	"united kingdom":     "gb",
	"london":             "gb",
	"scotland":           "gb",
	"edinburgh":          "gb",
	"england":            "gb",
	"britain":            "gb",
	"buckingham":         "gb",
	"isle of man":        "im",
	"ireland":            "ie",
	"dublin":             "ie",
	"deutschland":        "de",
	"germany":            "de",
	"aachen":             "de",
	"steglitz":           "de",
	"friedrichshain":     "de",
	"berghain":           "de",
	"bundestag":          "de",
	"grunewald":          "de",
	"charlottenburg":     "de",
	"wilmersdorf":        "de",
	"tempelhof":          "de",
	"schönefeld":         "de",
	"reichstag":          "de",
	"kassel":             "de",
	"kreuzberg":          "de",
	"ostsee":             "de",
	"nordsee":            "de",
	"wannsee":            "de",
	"berlin":             "de",
	"pfalz":              "de",
	"mannheim":           "de",
	"heidelberg":         "de",
	"stuttgart":          "de",
	"bisingen":           "de",
	"balingen":           "de",
	"hechingen":          "de",
	"swabian":            "de",
	"schwarzwald":        "de",
	"schwäbische":        "de",
	"albtrauf":           "de",
	"münchen":            "de",
	"württemberg":        "de",
	"bayern":             "de",
	"erfurt":             "de",
	"leipzig":            "de",
	"schwerin":           "de",
	"greifswald":         "de",
	"dresden":            "de",
	"nebelhorn":          "de",
	"neuschwanstein":     "de",
	"nürnberg":           "de",
	"würzburg":           "de",
	"munich":             "de",
	"frankfurt":          "de",
	"freiburg":           "de",
	"brandenburg":        "de",
	"hamburg":            "de",
	"tübingen":           "de",
	"tubingen":           "de",
	"köln":               "de",
	"königsee":           "de",
	"dortmund":           "de",
	"düsseldorf":         "de",
	"cologne":            "de",
	"saarland":           "de",
	"saarbrücken":        "de",
	"konstanz":           "de",
	"reichenau":          "de",
	"meckenheim":         "de",
	"wiesbaden":          "de",
	"lahnstein":          "de",
	"augsburg":           "de",
	"freinsheim":         "de",
	"speyer":             "de",
	"marburg":            "de",
	"mechtersheim":       "de",
	"dürkheim":           "de",
	"ulm":                "de",
	"zugspitze":          "de",
	"sächsische schweiz": "de",
	"latvia":             "lv",
	"lettland":           "lv",
	"lithuania":          "lt",
	"litauen":            "lt",
	"estonia":            "ee",
	"australia":          "au",
	"melbourne":          "au",
	"perth":              "au",
	"tasmania":           "au",
	"tasmanien":          "au",
	"sydney":             "au",
	"capetown":           "za",
	"durban":             "za",
	"pretoria":           "za",
	"kapstadt":           "za",
	"johannesburg":       "za",
	"south africa":       "za",
	"eswatini":           "sz",
	"swaziland":          "sz",
	"romania":            "ro",
	"ecuador":            "ec",
	"mexico":             "mx",
	"colombia":           "co",
	"california":         "us",
	"washington":         "us",
	"new york":           "us",
	"nyc":                "us",
	"florida":            "us",
	"cape canaveral":     "us",
	"san francisco":      "us",
	"oakland":            "us",
	"san diego":          "us",
	"los angeles":        "us",
	"seattle":            "us",
	"chicago":            "us",
	"miami":              "us",
	"dallas":             "us",
	"houston":            "us",
	"las vegas":          "us",
	"minneapolis":        "us",
	"kansas":             "us",
	"wisconsin":          "us",
	"michigan":           "us",
	"illinois":           "us",
	"boston":             "us",
	"massachusetts":      "us",
	"connecticut":        "us",
	"new jersey":         "us",
	"delaware":           "us",
	"orlando":            "us",
	"detroit":            "us",
	"nevada":             "us",
	"texas":              "us",
	"usa":                "us",
	"united states":      "us",
	"venice beach":       "us",
	"mongolia":           "mn",
	"chile":              "cl",
	"rwanda":             "rw",
	"istanbul":           "tr",
	"turkey":             "tr",
	"türkei":             "tr",
	"kyrgyzstan":         "kg",
	"bhutan":             "bt",
	"everest":            "np",
	"kathmandu":          "np",
	"nepal":              "np",
	"bangladesh":         "bd",
	"jordan":             "jo",
	"syria":              "sy",
	"lebanon":            "lb",
	"bulgaria":           "bg",
	"koprivshtitsa":      "bg",
	"melnik":             "bg",
	"sofia":              "bg",
	"corfu":              "gr",
	"greece":             "gr",
	"hellas":             "gr",
	"north korea":        "kp",
	"dprk":               "kp",
	"dpr korea":          "kp",
	"algeria":            "dz",
	"tunisia":            "tn",
	"libya":              "ly",
	"mauritania":         "mr",
	"gambia":             "gm",
	"senegal":            "sn",
	"guinea bissau":      "gw",
	"sierra leone":       "sl",
	"guinea":             "gn",
	"ivory coast":        "ci",
	"liberia":            "lr",
	"ghana":              "gh",
	"togo":               "tg",
	"burkina faso":       "bf",
	"benin":              "bj",
	"mali":               "ml",
	"niger":              "ne",
	"nigeria":            "ng",
	"sudan":              "sd",
	"central african":    "cf",
	"equatorial guinea":  "gq",
	"gabon":              "ga",
	"congo brazzaville":  "cg",
	"congo":              "cd",
	"uganda":             "ug",
	"kenya":              "ke",
	"somalia":            "so",
	"ethiopia":           "et",
	"djibouti":           "dj",
	"cameroon":           "cm",
	"namibia":            "na",
	"angola":             "ao",
	"burundi":            "bi",
	"tanzania":           "tz",
	"zambia":             "zm",
	"zimbabwe":           "zw",
	"rhodesia":           "zw",
	"mozambique":         "mz",
	"malawi":             "mw",
	"uzbekistan":         "uz",
	"tajikistan":         "tj",
	"kazakhstan":         "kz",
	"croatia":            "hr",
	"ljubljana":          "si",
	"slovenia":           "si",
	"turkmenistan":       "tm",
	"bolivia":            "bo",
	"guernsey":           "gg",
	"china":              "cn",
	"shanghai":           "cn",
	"上海市":                "cn",
	"peking":             "cn",
	"北京市":                "cn",
	"beijing":            "cn",
	"venezuela":          "ve",
	"virgin island":      "vg",
	"argentina":          "ar",
	"argentine":          "ar",
	"uruguay":            "uy",
	"paraguay":           "py",
	"suriname":           "sr",
	"guyana":             "gy",
	"nicaragua":          "ni",
	"costa rica":         "cr",
	"panama":             "pa",
	"honduras":           "hn",
	"belize":             "bz",
	"peru":               "pe",
	"portugal":           "pt",
	"eritrea":            "er",
	"iceland":            "is",
	"ísland":             "is",
	"afghanistan":        "af",
	"india":              "in",
	"indien":             "in",
	"indonesia":          "id",
	"iraq":               "iq",
	"irak":               "iq",
	"iran":               "ir",
	"persia":             "ir",
	"yemen":              "ye",
	"qatar":              "qa",
	"kuwait":             "kw",
	"oman":               "om",
	"east timor":         "tl",
	"pakistan":           "pk",
	"saudi arabia":       "sa",
	"south korea":        "kr",
	"united arab":        "ae",
	"uae":                "ae",
	"cyprus":             "cy",
	"dominica":           "dm",
	"haiti":              "ht",
	"hayti":              "ht",
	"cuba":               "cu",
	"new guinea":         "pg",
	"armenia":            "am",
	"azerbaijan":         "az",
	"malta":              "mt",
	"como":               "it",
	"cortina d'ampezzo":  "it",
	"italy":              "it",
	"milan":              "it",
	"milano":             "it",
	"mailand":            "it",
	"neapel":             "it",
	"palermo":            "it",
	"genua":              "it",
	"florenz":            "it",
	"bologna":            "it",
	"venezia":            "it",
	"venedig":            "it",
	"venice":             "it",
	"italien":            "it",
	"sicily":             "it",
	"trieste":            "it",
	"jersey island":      "je",
	"bahrain":            "bh",
	"japan":              "jp",
	"tokyo":              "jp",
	"東京都":                "jp",
	"fukushima":          "jp",
	"nippon":             "jp",
	"nihon":              "jp",
	"pilipinas":          "ph",
	"filipinas":          "ph",
	"philippines":        "ph",
	"madagascar":         "mg",
	"taiwan":             "tw",
	"taipei":             "tw",
	"cape verde":         "cv",
	"comoros":            "km",
	"mauritius":          "mu",
	"são tomé":           "st",
	"príncipe":           "st",
	"seychelles":         "sc",
	"seychellen":         "sc",
	"maldives":           "mv",
	"singapore":          "sg",
	"sri lanka":          "lk",
	"saint kitts":        "kn",
	"nevis":              "kn",
	"antigua":            "ag",
	"barbuda":            "ag",
	"montserrat":         "ms",
	"bahamas":            "bs",
	"turks island":       "tc",
	"caicos island":      "tc",
	"barbados":           "bb",
	"saint vincent":      "vc",
	"grenada":            "gd",
	"saint lucia":        "lc",
	"jamaica":            "jm",
	"trinidad":           "tt",
	"tobago":             "tt",
	"new zealand":        "nz",
	"kiribati":           "ki",
	"fiji":               "fj",
	"bligh island":       "fj",
	"marshall island":    "mh",
	"micronesia":         "fm",
	"nauru":              "nr",
	"palau":              "pw",
	"monaco":             "mc",
	"liechtenstein":      "li",
	"gibraltar":          "gi",
	"spain":              "es",
	"spanien":            "es",
	"andalusien":         "es",
	"andalusia":          "es",
	"canarias":           "es",
	"granada":            "es",
	"madrid":             "es",
	"barcelona":          "es",
	"córdoba":            "es",
	"seville":            "es",
	"málaga":             "es",
	"bilbao":             "es",
	"valencia":           "es",
	"españa":             "es",
	"espana":             "es",
	"canada":             "ca",
	"kanada":             "ca",
	"vancouver":          "ca",
	"british columbia":   "ca",
	"montreal":           "ca",
	"toronto":            "ca",
	"ottawa":             "ca",
	"quebec":             "ca",
	"ontario":            "ca",
	"alberta":            "ca",
	"israel":             "il",
	"holy land":          "il",
	"egypt":              "eg",
	"ägypten":            "eg",
	"aegypten":           "eg",
	"el salvador":        "sv",
	"guatemala":          "gt",
	"niue":               "nu",
	"south sudan":        "ss",
	"serbia":             "rs",
	"solomon island":     "sb",
	"samoa":              "ws",
	"gaborone":           "bw",
	"botswana":           "bw",
	"botsuana":           "bw",
	"saint helena":       "sh",
	"sandwich island":    "gs",
	"bermuda":            "bm",
	"british indian":     "io",
	"thailand":           "th",
	"kosovo":             "xk",
	"lesotho":            "ls",
	"brunei":             "bn",
	"malaysia":           "my",
	"luxembourg":         "lu",
	"anguilla":           "ai",
	"vanuatu":            "vu",
	"tuvalu":             "tv",
	"greenland":          "gl",
	"cook island":        "ck",
	"cayman island":      "ky",
	"falkland island":    "fk",
	"pitcairn island":    "pn",
	"tokelau":            "tk",
	"tonga":              "to",
	"chamonix":           "fr",
	"réunion":            "fr",
	"strassburg":         "fr",
	"strasbourg":         "fr",
	"straßburg":          "fr",
	"paris":              "fr",
	"amsterdam":          "nl",
	"beekse bergen":      "nl",
	"eindhoven":          "nl",
	"netherlands":        "nl",
	"holland":            "nl",
	"chad":               "td",
	"bosnia":             "ba",
	"herzegovina":        "ba",
	"norway":             "no",
	"norwegen":           "no",
	"morocco":            "ma",
	"palestine":          "ps",
	"mcdonald island":    "hm",
	"heard island":       "hm",
}
