package txt

var TitleReplacements = map[string]string{
	"Nyc":     "NYC",
	"Ny ":     "NY ",
	"Uae":     "UAE",
	"Usa":     "USA",
	"Amd ":    "AMD ",
	"Tiff":    "TIFF",
	"Ibm":     "IBM",
	"Usd":     "USD",
	"Gbp":     "GBP",
	"Chf":     "CHF",
	"Ceo":     "CEO",
	"Cto":     "CTO",
	"Cfo":     "CFO",
	"Cia ":    "CIA ",
	"Fbi":     "FBI",
	"Bnd":     "BND",
	"Fsb":     "FSB",
	"Nsa":     "NSA",
	"Lax ":    "LAX ",
	"Sfx":     "SFX",
	"Ber ":    "BER ",
	"Sfo":     "SFO",
	"Lh ":     "LH ",
	"Lhr":     "LHR",
	"Afl ":    "AFL ",
	"Nrl":     "NRL",
	"Nsw":     "NSW",
	"Qld":     "QLD",
	"Vic ":    "VIC ",
	"Iphone":  "iPhone",
	"Imac":    "iMac",
	"Ipad":    "iPad",
	"Macbook": "MacBook",
	" And ":   " and ",
	" Or ":    " or ",
	" A ":     " a ",
	" An ":    " an ",
	" To ":    " to ",
	" At ":    " at ",
	" By ":    " by ",
	" But ":   " but ",
	" For ":   " for ",
}
