import {$gettext} from "common/vm";

export default {
    cancel: $gettext("Cancel"),
    confirm: $gettext("Save"),
    save: $gettext("Save"),
    enabled: $gettext("Enabled"),
    disabled: $gettext("Disabled"),
    name: $gettext("Name"),
    url: $gettext("Service URL"),
    user: $gettext("Username"),
    pass: $gettext("Password"),
    owner: $gettext("Owner"),
    apiKey: $gettext("API Key"),
    AccType: $gettext("Type"),
    SharePath: $gettext("Default Folder"),
    ShareSize: $gettext("Size"),
    Expires: $gettext("Expires"),
    SyncPath: $gettext("Folder"),
    SyncInterval: $gettext("Interval"),
    SyncFilenames: $gettext("Preserve filenames"),
    SyncStart: $gettext("Start"),
    SyncDownload: $gettext("Download remote files"),
    SyncUpload: $gettext("Upload local files"),
    SyncDelete: $gettext("Remote delete"),
    SyncRaw: $gettext("Sync raw images"),
    language: $gettext("Language"),
    theme: $gettext("Theme"),
    mapsAnimate: $gettext("Animation"),
    mapsStyle: $gettext("Style"),
    rescan: $gettext("Complete rescan"),
    thumbs: $gettext("Create thumbnails"),
    move: $gettext("Remove imported files"),
    group: $gettext("Group Sequential"),
    archive: $gettext("Archive"),
    private: $gettext("Hide Private"),
    review: $gettext("Quality Filter"),
    places: $gettext("Places"),
    originals: $gettext("Originals"),
    moments: $gettext("Moments"),
    labels: $gettext("Labels"),
    import: $gettext("Import"),
    upload: $gettext("Upload"),
    download: $gettext("Download"),
    edit: $gettext("Edit"),
    share: $gettext("Share"),
    logs: $gettext("Logs"),
    library: $gettext("Library"),
    convert: $gettext("Convert to JPEG"),
};
