// Code generated by hand as a check-gorm-v1 fixture; DO NOT EDIT.

package sample

import "github.com/jinzhu/gorm"

// Generated holds a site the check must skip.
func Generated(db *gorm.DB) bool {
	return db.RecordNotFound()
}
