package config

import (
	"fmt"
	"math"
	"strconv"

	"github.com/photoprism/photoprism/internal/ai/classify"
	"github.com/photoprism/photoprism/internal/ai/face"
	"github.com/photoprism/photoprism/internal/ai/nsfw"
	"github.com/photoprism/photoprism/internal/ai/vision"
	"github.com/photoprism/photoprism/pkg/clean"
)

// VisionStatus returns the lines `photoprism vision status` prints above the tables, stating which
// model each computer vision feature uses, when it runs, and what is keeping it from running.
func (c *Config) VisionStatus() []string {
	if c == nil || vision.Config == nil {
		return []string{"Computer vision is unavailable."}
	}

	lines := []string{c.visionLabelsStatus(), c.visionNsfwStatus()}
	lines = append(lines, c.visionFacesStatus()...)

	return append(lines, visionCaptionStatus())
}

// visionFacesStatus states whether faces are processed and why the embedding model generates no
// vectors, leaving the clustering state to "photoprism faces status".
func (c *Config) visionFacesStatus() []string {
	if !c.DisableFaces() && vision.Config.Model(vision.ModelTypeFace) == nil {
		return []string{"Face detection and recognition are disabled in the vision.yml file."}
	}

	lines := c.FaceStatus()[:1]

	// A load error or pause only matters while an embedding model is in force.
	if c.DisableFaces() || c.EffectiveFaceModel() == face.ModelNone {
		return lines
	} else if status := c.faceEmbedderStatus(); status != "" {
		lines = append(lines, status)
	}

	return lines
}

// VisionReportSections returns the computer vision configuration grouped for `photoprism vision status`.
func (c *Config) VisionReportSections() []StatusSection {
	if c == nil || vision.Config == nil {
		return nil
	}

	cols := []string{"Name", "Value"}
	thresholds := vision.Config.Thresholds

	general := StatusSection{Title: "Global Options", Cols: cols, Rows: [][]string{
		{"vision-yaml", c.VisionYaml()},
		{"vision-api", fmt.Sprintf("%t", c.VisionApi())},
		{"vision-uri", clean.UriRedacted(c.VisionUri())},
		{"vision-key", maskedSecret(c.VisionKey())},
		{"vision-schedule", c.VisionSchedule()},
		{"vision-filter", c.VisionFilter()},
		{"models-path", c.ModelsPath()},
		{"onnx-provider", c.OnnxProvider().String()},
	}}

	labels := StatusSection{Title: "Labels", Cols: cols, Rows: [][]string{
		{"labels-model", c.labelsModelReport()},
		{"label-model-path", c.LabelModelPath()},
		{"label-model-runtime", c.LabelModelRuntime()},
		{"Thresholds.Confidence", fmt.Sprintf("%d", thresholds.GetConfidence())},
		{"Thresholds.Topicality", fmt.Sprintf("%d", thresholds.GetTopicality())},
	}}

	// The deprecated option is reported only while it still decides something.
	if c.options.DisableClassification && c.LabelModelSetting() == classify.ModelNone {
		labels.Rows = append(labels.Rows, []string{"disable-classification", "true"})
	}

	detector := vision.Config.Model(vision.ModelTypeNsfw)

	nsfwSection := StatusSection{Title: "NSFW Detection", Cols: cols, Rows: [][]string{
		{"nsfw-model", c.nsfwModelReport()},
		{"nsfw-model-path", c.NsfwModelPath()},
		{"nsfw-model-runtime", c.NsfwModelRuntime()},
		{"detect-nsfw", fmt.Sprintf("%t", c.DetectNSFW())},
		{"upload-nsfw", fmt.Sprintf("%t", c.UploadNSFW())},
		{"Thresholds.NSFWIndex", nsfwThresholdReport(thresholds.NSFWIndexIsSet(), thresholds.GetNSFWIndex(), detector)},
		{"Thresholds.NSFWUpload", nsfwThresholdReport(thresholds.NSFWUploadIsSet(), thresholds.GetNSFWUpload(), detector)},
		{"Thresholds.NSFW", fmt.Sprintf("%d", thresholds.GetNSFW())},
	}}

	return []StatusSection{general, labels, nsfwSection}
}

// visionLabelsStatus states which model generates labels and when, or why none does.
func (c *Config) visionLabelsStatus() string {
	effective := c.EffectiveLabelModel()
	model := vision.Config.Model(vision.ModelTypeLabels)

	switch {
	case c.LabelModelSetting() == classify.ModelNone:
		return "Image classification is disabled."
	case effective == classify.ModelNone && model == nil:
		return "Image classification is disabled in the vision.yml file."
	case effective == classify.ModelNone || model == nil:
		return "Image classification is unavailable, because no label model is installed."
	case visionModelMissing(model, c.ModelsPath()):
		return fmt.Sprintf("Labels are not generated, because %s is not installed.", clean.Log(model.Name))
	case model.RunType() == vision.RunNever:
		return fmt.Sprintf("Labels are not generated, because %s is configured to never run.", c.visionModelSummary(model))
	}

	return fmt.Sprintf("Labels are generated by %s %s.", c.visionModelSummary(model), visionRunPhrase(model))
}

// visionNsfwStatus states how NSFW content is detected during indexing and uploads, or why it is not.
func (c *Config) visionNsfwStatus() string {
	switch c.NSFWModelSetting() {
	case nsfw.ModelNone:
		return "NSFW detection is disabled."
	case nsfw.ModelName("labels"):
		switch {
		case !c.DetectNSFW():
			return "NSFW content is not flagged, because detect-nsfw is off, and uploads are not screened in labels mode."
		case !labelsModelReturnsNSFW():
			return "NSFW content is not flagged, because the labels model cannot return NSFW fields, and uploads are not screened in labels mode."
		}

		return "NSFW content is flagged based on the labels model response, and uploads are not screened in labels mode."
	}

	model := vision.Config.Model(vision.ModelTypeNsfw)

	switch {
	case c.EffectiveNSFWModel() == nsfw.ModelNone && model == nil:
		return "NSFW detection is disabled in the vision.yml file."
	case c.EffectiveNSFWModel() == nsfw.ModelNone || model == nil:
		return "NSFW detection is unavailable, because no detector is installed."
	case visionModelMissing(model, c.ModelsPath()):
		return fmt.Sprintf("NSFW detection is unavailable, because %s is not installed.", clean.Log(model.Name))
	}

	summary := c.visionModelSummary(model)

	// Indexing requires detect-nsfw and a schedule, while uploads are screened by the same detector
	// whatever its schedule, unless upload-nsfw allows offensive content.
	notIndexed := "detect-nsfw is off"

	if c.DetectNSFW() && model.RunType() == vision.RunNever {
		notIndexed = "the detector is configured to never run"
	}

	switch index, screen := c.DetectNSFW() && model.RunType() != vision.RunNever, !c.UploadNSFW(); {
	case index && screen:
		return fmt.Sprintf("NSFW content is flagged by %s %s, and uploads are screened.", summary, visionRunPhrase(model))
	case index:
		return fmt.Sprintf("NSFW content is flagged by %s %s, but uploads are not screened, because upload-nsfw is on.", summary, visionRunPhrase(model))
	case screen:
		return fmt.Sprintf("Uploads are screened by %s, but indexed content is not flagged, because %s.", summary, notIndexed)
	default:
		return fmt.Sprintf("NSFW detection with %s is not used, because %s and upload-nsfw is on.", summary, notIndexed)
	}
}

// visionCaptionStatus states which model generates captions and when, or that none does.
func visionCaptionStatus() string {
	model := vision.Config.Model(vision.ModelTypeCaption)

	if model == nil {
		return "Caption generation is disabled."
	} else if model.RunType() == vision.RunNever {
		return "Captions are not generated, because the caption model is configured to never run."
	}

	name, _, _ := model.GetModel()

	return fmt.Sprintf("Captions are generated by %s through %s %s.", clean.Log(name), model.EngineName(), visionRunPhrase(model))
}

// visionModelSummary names a model with the service or execution provider it runs on.
func (c *Config) visionModelSummary(model *vision.Model) string {
	name, _, _ := model.GetModel()

	if model.Service.UriUnresolved() {
		return fmt.Sprintf("%s with an unresolved service URI", clean.Log(name))
	} else if visionModelRemote(model) {
		return fmt.Sprintf("%s through %s", clean.Log(name), model.EngineName())
	}

	return fmt.Sprintf("%s on the %s provider", clean.Log(name), c.OnnxProvider())
}

// visionRunPhrase describes when a model runs, as the end of a status sentence.
func visionRunPhrase(model *vision.Model) string {
	switch afterIndex, onSchedule := model.ShouldRun(vision.RunNewlyIndexed), model.ShouldRun(vision.RunOnSchedule); {
	case model.RunType() == vision.RunAlways:
		return "in every context"
	case model.ShouldRun(vision.RunOnIndex):
		return "during indexing"
	case afterIndex && onSchedule:
		return "after indexing and on schedule"
	case afterIndex:
		return "after indexing"
	case onSchedule:
		return "on schedule"
	default:
		return "only when requested"
	}
}

// visionModelMissing reports whether a local model names a registered artifact that is not
// installed. Custom and remote models are not checked, so it never reports them as missing.
func visionModelMissing(model *vision.Model, modelsPath string) bool {
	if visionModelRemote(model) {
		return false
	}

	switch model.Type {
	case vision.ModelTypeLabels:
		if description := classify.FindModel(classify.ModelName(model.Name)); description != nil {
			return !description.Installed(modelsPath)
		}
	case vision.ModelTypeNsfw:
		if description := nsfw.FindModel(nsfw.ModelName(model.Name)); description != nil {
			return !description.Installed(modelsPath)
		}
	}

	return false
}

// labelsModelReport renders the labels mode with the model it resolves to.
func (c *Config) labelsModelReport() string {
	setting := c.LabelModelSetting()

	if setting == classify.ModelNone {
		return string(setting)
	}

	return fmt.Sprintf("%s (%s)", setting, c.EffectiveLabelModel())
}

// nsfwModelReport renders the NSFW mode with the detector it resolves to.
func (c *Config) nsfwModelReport() string {
	setting := c.NSFWModelSetting()

	if setting != nsfw.ModelAuto {
		return string(setting)
	}

	return fmt.Sprintf("%s (%s)", setting, c.EffectiveNSFWModel())
}

// nsfwThresholdReport renders a detector threshold, or the threshold the detector applies when
// none is configured: its calibrated default, or the fallback for a remote or custom detector.
func nsfwThresholdReport(configured bool, value int, model *vision.Model) string {
	if configured {
		return fmt.Sprintf("%d", value)
	} else if model == nil {
		return "auto"
	}

	if visionModelRemote(model) {
		return fmt.Sprintf("auto (%d)", vision.DefaultNSFWThreshold)
	}

	threshold := nsfw.DefaultThreshold

	if description := nsfw.FindModel(nsfw.ModelName(model.Name)); description != nil {
		threshold = description.DefaultThreshold
	} else if model.DefaultThreshold > 0 && model.DefaultThreshold <= 1 {
		threshold = model.DefaultThreshold
	}

	// Detectors are calibrated as a fraction, while vision.yml sets thresholds in percent.
	return fmt.Sprintf("auto (%s)", strconv.FormatFloat(math.Round(float64(threshold)*1000)/10, 'f', -1, 64))
}
