package config

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/photoprism/photoprism/internal/ai/classify"
	"github.com/photoprism/photoprism/internal/ai/nsfw"
	"github.com/photoprism/photoprism/internal/ai/vision"
)

// newVisionReportConfig returns a config with the default label and NSFW models installed in a
// temporary models path, applied to the vision configuration passed.
func newVisionReportConfig(t *testing.T, models *vision.ConfigValues) *Config {
	t.Helper()

	withVisionConfig(t, models)

	c := NewConfig(CliTestContext())
	c.options.ModelsPath = t.TempDir()
	c.options.OnnxProvider = "cpu"
	c.options.LabelsModel = "auto"
	c.options.NsfwModel = "auto"
	c.options.DetectNSFW = true
	c.options.UploadNSFW = false

	installVisionTestArtifact(t, c.ModelsPath(), string(classify.DefaultModelName()), classify.DefaultModel().ONNX.File)
	installVisionTestArtifact(t, c.ModelsPath(), string(nsfw.ModelYahoo), nsfw.FindModel(nsfw.ModelYahoo).ONNX.File)

	c.applyLabelModel()
	c.applyNSFWModel()

	return c
}

// newRemoteVisionModel returns a model of the specified type served by Ollama.
func newRemoteVisionModel(modelType vision.ModelType, run vision.RunType) *vision.Model {
	model := &vision.Model{Type: modelType, Engine: "ollama", Name: "qwen3-vl:4b-instruct", Run: run}
	model.ApplyEngineDefaults()
	return model
}

func TestConfig_VisionStatus(t *testing.T) {
	t.Run("Default", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		lines := c.VisionStatus()
		require.Len(t, lines, 3+len(c.visionFacesStatus()))
		assert.Equal(t, "Labels are generated by efficientformerv2_s2 on the cpu provider during indexing.", lines[0])
		assert.Equal(t, "NSFW content is flagged by yahoo_open_nsfw on the cpu provider during indexing, and uploads are screened.", lines[1])
		assert.Equal(t, c.FaceStatus()[0], lines[2])
		assert.Contains(t, lines[len(lines)-1], "Captions are generated by ")
		assert.Contains(t, lines[len(lines)-1], " only when requested.")
	})
	t.Run("Nil", func(t *testing.T) {
		var c *Config
		assert.Equal(t, []string{"Computer vision is unavailable."}, c.VisionStatus())
		assert.Nil(t, c.VisionReportSections())
	})
}

func TestConfig_VisionReportSections(t *testing.T) {
	t.Run("Default", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		sections := c.VisionReportSections()
		require.Len(t, sections, 3)
		assert.Equal(t, "Global Options", sections[0].Title)
		assert.Contains(t, sections[0].Rows, []string{"onnx-provider", "cpu"})
		assert.Equal(t, "Labels", sections[1].Title)
		assert.Contains(t, sections[1].Rows, []string{"labels-model", "auto (efficientformerv2_s2)"})
		assert.NotContains(t, sections[1].Rows, []string{"disable-classification", "true"})
		assert.Equal(t, "NSFW Detection", sections[2].Title)
		assert.Contains(t, sections[2].Rows, []string{"nsfw-model", "auto (yahoo_open_nsfw)"})
		assert.Contains(t, sections[2].Rows, []string{"upload-nsfw", "false"})
		assert.Contains(t, sections[2].Rows, []string{"Thresholds.NSFWIndex", "auto (32.7)"})
		assert.Contains(t, sections[2].Rows, []string{"Thresholds.NSFW", "75"})
	})
	t.Run("DeprecatedDisableClassification", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.LabelsModel = ""
		c.options.DisableClassification = true
		rows := c.VisionReportSections()[1].Rows
		assert.Contains(t, rows, []string{"labels-model", "none"})
		assert.Contains(t, rows, []string{"disable-classification", "true"})
	})
	t.Run("DeprecatedIgnored", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.DisableClassification = true
		assert.NotContains(t, c.VisionReportSections()[1].Rows, []string{"disable-classification", "true"})
	})
}

func TestConfig_visionLabelsStatus(t *testing.T) {
	t.Run("Disabled", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.LabelsModel = "none"
		c.applyLabelModel()
		assert.Equal(t, "Image classification is disabled.", c.visionLabelsStatus())
	})
	t.Run("DisabledInVisionYaml", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[0].Disabled = true
		c := newVisionReportConfig(t, config)
		assert.Equal(t, "Image classification is disabled in the vision.yml file.", c.visionLabelsStatus())
	})
	t.Run("NoneInstalled", func(t *testing.T) {
		withVisionConfig(t, vision.NewConfig())
		c := NewConfig(CliTestContext())
		c.options.ModelsPath = t.TempDir()
		c.options.LabelsModel = "auto"
		c.applyLabelModel()
		assert.Equal(t, "Image classification is unavailable, because no label model is installed.", c.visionLabelsStatus())
	})
	t.Run("NamedNotInstalled", func(t *testing.T) {
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{vision.NewLabelModel(classify.ModelRepViTM10)}})
		assert.Equal(t, "Labels are not generated, because repvit_m1_0 is not installed.", c.visionLabelsStatus())
	})
	t.Run("Never", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[0].Run = vision.RunNever
		c := newVisionReportConfig(t, config)
		assert.Equal(t, "Labels are not generated, because efficientformerv2_s2 on the cpu provider is configured to never run.", c.visionLabelsStatus())
	})
	t.Run("Remote", func(t *testing.T) {
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeLabels, vision.RunOnSchedule)}})
		assert.Equal(t, "Labels are generated by qwen3-vl:4b-instruct through ollama on schedule.", c.visionLabelsStatus())
	})
}

func TestConfig_visionNsfwStatus(t *testing.T) {
	t.Run("None", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.NsfwModel = "none"
		assert.Equal(t, "NSFW detection is disabled.", c.visionNsfwStatus())
	})
	t.Run("Labels", func(t *testing.T) {
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeLabels, vision.RunAuto)}})
		c.options.NsfwModel = "labels"
		assert.Equal(t, "NSFW content is flagged based on the labels model response, and uploads are not screened in labels mode.", c.visionNsfwStatus())
		c.options.DetectNSFW = false
		assert.Equal(t, "NSFW content is not flagged, because detect-nsfw is off, and uploads are not screened in labels mode.", c.visionNsfwStatus())
	})
	t.Run("LabelsWithoutNSFWFields", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.NsfwModel = "labels"
		assert.Equal(t, "NSFW content is not flagged, because the labels model cannot return NSFW fields, and uploads are not screened in labels mode.", c.visionNsfwStatus())
	})
	t.Run("DisabledInVisionYaml", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[1].Disabled = true
		c := newVisionReportConfig(t, config)
		assert.Equal(t, "NSFW detection is disabled in the vision.yml file.", c.visionNsfwStatus())
	})
	t.Run("NoneInstalled", func(t *testing.T) {
		withVisionConfig(t, vision.NewConfig())
		c := NewConfig(CliTestContext())
		c.options.ModelsPath = t.TempDir()
		c.options.NsfwModel = "auto"
		c.applyNSFWModel()
		assert.Equal(t, "NSFW detection is unavailable, because no detector is installed.", c.visionNsfwStatus())
	})
	t.Run("NamedNotInstalled", func(t *testing.T) {
		detector := vision.NewNsfwModel(nsfw.ModelFalconsai)
		detector.Default = false
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{detector}})
		assert.Equal(t, "NSFW detection is unavailable, because falconsai_nsfw_image_detection_224 is not installed.", c.visionNsfwStatus())
	})
	t.Run("IndexOnly", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.UploadNSFW = true
		assert.Equal(t, "NSFW content is flagged by yahoo_open_nsfw on the cpu provider during indexing, but uploads are not screened, because upload-nsfw is on.", c.visionNsfwStatus())
	})
	t.Run("UploadsOnly", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.DetectNSFW = false
		assert.Equal(t, "Uploads are screened by yahoo_open_nsfw on the cpu provider, but indexed content is not flagged, because detect-nsfw is off.", c.visionNsfwStatus())
	})
	t.Run("NeverIsNotIndexing", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[1].Run = vision.RunNever
		c := newVisionReportConfig(t, config)
		assert.Equal(t, "Uploads are screened by yahoo_open_nsfw on the cpu provider, but indexed content is not flagged, because the detector is configured to never run.", c.visionNsfwStatus())
		c.options.UploadNSFW = true
		assert.Equal(t, "NSFW detection with yahoo_open_nsfw on the cpu provider is not used, because the detector is configured to never run and upload-nsfw is on.", c.visionNsfwStatus())
	})
	t.Run("Unused", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.DetectNSFW = false
		c.options.UploadNSFW = true
		assert.Equal(t, "NSFW detection with yahoo_open_nsfw on the cpu provider is not used, because detect-nsfw is off and upload-nsfw is on.", c.visionNsfwStatus())
	})
	t.Run("Remote", func(t *testing.T) {
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeNsfw, vision.RunAuto)}})
		assert.Equal(t, "NSFW content is flagged by qwen3-vl:4b-instruct through ollama after indexing and on schedule, and uploads are screened.", c.visionNsfwStatus())
	})
}

func TestVisionCaptionStatus(t *testing.T) {
	t.Run("Disabled", func(t *testing.T) {
		withVisionConfig(t, &vision.ConfigValues{})
		assert.Equal(t, "Caption generation is disabled.", visionCaptionStatus())
	})
	t.Run("Never", func(t *testing.T) {
		withVisionConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeCaption, vision.RunNever)}})
		assert.Equal(t, "Captions are not generated, because the caption model is configured to never run.", visionCaptionStatus())
	})
	t.Run("Manual", func(t *testing.T) {
		withVisionConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeCaption, vision.RunManual)}})
		assert.Equal(t, "Captions are generated by qwen3-vl:4b-instruct through ollama only when requested.", visionCaptionStatus())
	})
}

func TestConfig_visionFacesStatus(t *testing.T) {
	t.Run("Default", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		assert.Equal(t, c.FaceStatus()[:1], c.visionFacesStatus())
	})
	t.Run("DisabledInVisionYaml", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[2].Disabled = true
		c := newVisionReportConfig(t, config)
		assert.Equal(t, []string{"Face detection and recognition are disabled in the vision.yml file."}, c.visionFacesStatus())
	})
	t.Run("DisableFaces", func(t *testing.T) {
		config := vision.NewConfig()
		config.Models[2].Disabled = true
		c := newVisionReportConfig(t, config)
		c.options.DisableFaces = true
		assert.Equal(t, []string{"Face detection and recognition are disabled."}, c.visionFacesStatus())
	})
}

// TestConfig_visionStatusServiceUri verifies that models routed to the global service URI are
// reported as remote, as they are when the server runs them.
func TestConfig_visionStatusServiceUri(t *testing.T) {
	previous := vision.ServiceUri
	t.Cleanup(func() { vision.ServiceUri = previous })
	vision.ServiceUri = "https://vision.example.com/api/v1/vision"

	c := newVisionReportConfig(t, vision.NewConfig())
	assert.Equal(t, "Labels are generated by efficientformerv2_s2 through vision during indexing.", c.visionLabelsStatus())
	assert.Empty(t, c.LabelModelPath())
	assert.Empty(t, c.NsfwModelPath())
	assert.Contains(t, c.VisionReportSections()[2].Rows, []string{"Thresholds.NSFWIndex", "auto (75)"})
}

func TestConfig_visionModelSummary(t *testing.T) {
	c := NewConfig(CliTestContext())
	c.options.OnnxProvider = "cuda"
	t.Run("Local", func(t *testing.T) {
		assert.Equal(t, "efficientformerv2_s2 on the cuda provider", c.visionModelSummary(vision.NewLabelModel(classify.DefaultModelName())))
	})
	t.Run("Remote", func(t *testing.T) {
		assert.Equal(t, "qwen3-vl:4b-instruct through ollama", c.visionModelSummary(newRemoteVisionModel(vision.ModelTypeLabels, vision.RunAuto)))
	})
	t.Run("UnresolvedUri", func(t *testing.T) {
		model := &vision.Model{Type: vision.ModelTypeLabels, Name: "remote", Service: vision.Service{Uri: "${VISION_TEST_MISSING_URI}"}}
		assert.Equal(t, "remote with an unresolved service URI", c.visionModelSummary(model))
	})
}

func TestVisionRunPhrase(t *testing.T) {
	cases := []struct {
		name  string
		model *vision.Model
		want  string
	}{
		{"Always", &vision.Model{Type: vision.ModelTypeLabels, Run: vision.RunAlways}, "in every context"},
		{"DefaultLabels", vision.NewLabelModel(classify.DefaultModelName()), "during indexing"},
		{"OnIndex", newRemoteVisionModel(vision.ModelTypeLabels, vision.RunOnIndex), "during indexing"},
		{"Manual", newRemoteVisionModel(vision.ModelTypeCaption, vision.RunManual), "only when requested"},
		{"OnSchedule", newRemoteVisionModel(vision.ModelTypeLabels, vision.RunOnSchedule), "on schedule"},
		{"OnDemand", newRemoteVisionModel(vision.ModelTypeLabels, vision.RunOnDemand), "after indexing and on schedule"},
		{"NewlyIndexed", newRemoteVisionModel(vision.ModelTypeLabels, vision.RunNewlyIndexed), "after indexing"},
		{"RemoteAuto", newRemoteVisionModel(vision.ModelTypeLabels, vision.RunAuto), "after indexing and on schedule"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, visionRunPhrase(tc.model))
		})
	}
}

func TestVisionModelMissing(t *testing.T) {
	modelsPath := t.TempDir()
	t.Run("RegisteredMissing", func(t *testing.T) {
		assert.True(t, visionModelMissing(vision.NewLabelModel(classify.DefaultModelName()), modelsPath))
		assert.True(t, visionModelMissing(vision.NewNsfwModel(nsfw.ModelYahoo), modelsPath))
	})
	t.Run("RegisteredInstalled", func(t *testing.T) {
		installVisionTestArtifact(t, modelsPath, string(nsfw.ModelYahoo), nsfw.FindModel(nsfw.ModelYahoo).ONNX.File)
		assert.False(t, visionModelMissing(vision.NewNsfwModel(nsfw.ModelYahoo), modelsPath))
	})
	t.Run("Custom", func(t *testing.T) {
		assert.False(t, visionModelMissing(&vision.Model{Type: vision.ModelTypeLabels, Name: "custom_21k"}, modelsPath))
	})
	t.Run("Remote", func(t *testing.T) {
		assert.False(t, visionModelMissing(newRemoteVisionModel(vision.ModelTypeLabels, vision.RunAuto), modelsPath))
	})
	t.Run("Caption", func(t *testing.T) {
		assert.False(t, visionModelMissing(&vision.Model{Type: vision.ModelTypeCaption, Name: "caption"}, modelsPath))
	})
}

func TestConfig_labelsModelReport(t *testing.T) {
	t.Run("Auto", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		assert.Equal(t, "auto (efficientformerv2_s2)", c.labelsModelReport())
	})
	t.Run("Remote", func(t *testing.T) {
		c := newVisionReportConfig(t, &vision.ConfigValues{Models: vision.Models{newRemoteVisionModel(vision.ModelTypeLabels, vision.RunAuto)}})
		assert.Equal(t, "auto (qwen3-vl:4b-instruct)", c.labelsModelReport())
	})
	t.Run("None", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.LabelsModel = "none"
		assert.Equal(t, "none", c.labelsModelReport())
	})
}

func TestConfig_nsfwModelReport(t *testing.T) {
	t.Run("Auto", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		assert.Equal(t, "auto (yahoo_open_nsfw)", c.nsfwModelReport())
	})
	t.Run("Labels", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.NsfwModel = "labels"
		assert.Equal(t, "labels", c.nsfwModelReport())
	})
	t.Run("None", func(t *testing.T) {
		c := newVisionReportConfig(t, vision.NewConfig())
		c.options.NsfwModel = "none"
		assert.Equal(t, "none", c.nsfwModelReport())
	})
}

func TestNsfwThresholdReport(t *testing.T) {
	t.Run("Configured", func(t *testing.T) {
		assert.Equal(t, "60", nsfwThresholdReport(true, 60, vision.NewNsfwModel(nsfw.ModelYahoo)))
	})
	t.Run("NoDetector", func(t *testing.T) {
		assert.Equal(t, "auto", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, nil))
	})
	t.Run("Calibrated", func(t *testing.T) {
		assert.Equal(t, "auto (32.7)", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, vision.NewNsfwModel(nsfw.ModelYahoo)))
		assert.Equal(t, "auto (52.9)", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, &vision.Model{Type: vision.ModelTypeNsfw, Name: string(nsfw.ModelFalconsai)}))
	})
	t.Run("Remote", func(t *testing.T) {
		assert.Equal(t, "auto (75)", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, newRemoteVisionModel(vision.ModelTypeNsfw, vision.RunAuto)))
	})
	t.Run("Custom", func(t *testing.T) {
		assert.Equal(t, "auto (80)", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, &vision.Model{Type: vision.ModelTypeNsfw, Name: "custom", DefaultThreshold: 0.8}))
		assert.Equal(t, "auto (98)", nsfwThresholdReport(false, vision.DefaultNSFWThreshold, &vision.Model{Type: vision.ModelTypeNsfw, Name: "custom", DefaultThreshold: 75}))
	})
}
