package sortby

const (
	Default     = ""
	Relevance   = "relevance"
	Duration    = "duration"
	Size        = "size"
	Count       = "count"
	Newest      = "newest"
	Oldest      = "oldest"
	Added       = "added"
	Imported    = "imported"
	Edited      = "edited"
	Updated     = "updated"
	Deleted     = "deleted"
	Place       = "place"
	Moment      = "moment"
	Favorites   = "favorites"
	Name        = "name"
	NameReverse = "name_reverse"
	Title       = "title"
	Path        = "path"
	Slug        = "slug"
	Category    = "category"
	Similar     = "similar"
	Random      = "random"
	Invalid     = "invalid"
	LastActive  = "last_active"
	SessExpires = "sess_expires"
	ClientName  = "client_name"
	CreatedAt   = "created_at"
)
