package sortby

const (
	Default     = ""
	Relevance   = "relevance"
	Duration    = "duration"
	Size        = "size"
	Count       = "count"
	Newest      = "newest"
	Oldest      = "oldest"
	Added       = "added"
	Imported    = "imported"
	Archived    = "archived"
	Edited      = "edited"
	Created     = "created"
	CreatedAt   = "created_at"
	Updated     = "updated"
	UpdatedAt   = "updated_at"
	Login       = "login"
	LoginAt     = "login_at"
	Deleted     = "deleted"
	DeletedAt   = "deleted_at"
	Place       = "place"
	Moment      = "moment"
	Favorites   = "favorites"
	Name        = "name"
	DisplayName = "display_name"
	NameReverse = "name_reverse"
	Email       = "email"
	Title       = "title"
	Path        = "path"
	Slug        = "slug"
	Category    = "category"
	Similar     = "similar"
	Random      = "random"
	Invalid     = "invalid"
	LastActive  = "last_active"
	SessExpires = "sess_expires"
	ClientName  = "client_name"
)
