export default {
  global: {
    ripple: false,
  },
  VBtn: {
    flat: true,
    variant: "flat",
    ripple: true,
  },
  VSwitch: {
    flat: true,
    density: "compact",
    baseColor: "switch",
    color: "surface-variant",
    minWidth: 32,
    variant: "flat",
    validateOn: "invalid-input",
    hideDetails: "auto",
    falseValue: false,
    ripple: false,
  },
  VRating: {
    density: "compact",
    color: "on-surface",
    activeColor: "surface-variant",
    ripple: false,
  },
  VForm: {
    validateOn: "invalid-input",
  },
  VCheckbox: {
    density: "compact",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
    ripple: false,
  },
  VTextField: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VTextarea: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VOtpInput: {
    variant: "outlined",
    baseColor: "on-surface-variant",
    validateOn: "invalid-input",
    autofocus: false,
  },
  VChip: {
    closable: true,
    rounded: true,
    flat: true,
    ripple: false,
    variant: "flat",
    color: "highlight",
    density: "default",
  },
  VAutocomplete: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
    hideNoData: true,
  },
  VCombobox: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VMenu: {
    origin: "auto",
    location: "bottom end",
    locationStrategy: "connected",
    density: "compact",
    transition: "slide-y-transition",
    openOnClick: true,
    openOnFocus: false,
    closeOnBack: true,
    closeOnContentClick: true,
    persistent: false,
    scrim: false,
    opacity: 0,
    zIndex: 1,
  },
  VSnackbar: {
    origin: "auto",
    location: "bottom center",
    variant: "flat",
    rounded: "pill",
    transition: false,
    attach: true,
    closeOnBack: true,
    closeOnContentClick: false,
    openOnFocus: false,
    openOnClick: false,
    openOnHover: false,
    timeout: -1,
    openDelay: 0,
    closeDelay: 0,
  },
  VSpeedDial: {
    attach: true,
    closeOnBack: true,
    closeOnContentClick: true,
    location: "top",
    transition: "slide-y-reverse-transition",
  },
  VSelect: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VSlider: {
    ripple: false,
    focused: false,
    elevation: 0,
    trackSize: 3,
    thumbSize: 18,
    hideDetails: "auto",
  },
  VCard: {
    density: "compact",
    color: "background",
    flat: true,
    ripple: false,
    transition: false,
  },
  VTab: {
    color: "on-surface",
    baseColor: "on-surface-variant",
    ripple: false,
  },
  VTabs: {
    grow: true,
    elevation: 0,
    color: "on-surface",
    bgColor: "secondary",
    baseColor: "secondary",
  },
  VTable: {
    density: "comfortable",
  },
  VToolbar: {
    flat: true,
    transition: false,
  },
  VNavigationDrawer: {
    width: 270,
    railWidth: 70,
    mobileBreakpoint: 960,
    location: "start",
    touchless: true,
    scrim: true,
  },
  VListItem: {
    ripple: false,
  },
  VDataTable: {
    color: "background",
    itemsPerPage: -1,
    hover: true,
  },
  VImg: {
    transition: false,
  },
  VDialog: {
    scrim: true,
    scrollable: true,
    retainFocus: false,
    transition: false,
    persistent: true,
    openDelay: 0,
    closeDelay: 0,
    attach: document.body,
    tabindex: -1,
  },
  VOverlay: {
    transition: false,
    openDelay: 0,
    closeDelay: 0,
  },
  VExpansionPanel: {
    tile: true,
    ripple: false,
  },
  VExpansionPanels: {
    flat: true,
    tile: true,
    static: true,
    variant: "accordion",
    bgColor: "secondary",
    ripple: false,
  },
  VProgressLinear: {
    height: 10,
    rounded: true,
    color: "surface-variant",
  },
};
